// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: services/problem/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceProto          `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Server        *ServerProto           `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Data          *DataProto             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Storage       *StorageProto          `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	Registry      *RegistryProto         `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`
	InternalAuth  *InternalAuthProto     `protobuf:"bytes,6,opt,name=internal_auth,json=internalAuth,proto3" json:"internal_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetService() *ServiceProto {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Bootstrap) GetServer() *ServerProto {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *DataProto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetStorage() *StorageProto {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *RegistryProto {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetInternalAuth() *InternalAuthProto {
	if x != nil {
		return x.InternalAuth
	}
	return nil
}

type InternalAuthProto struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyFile     string                 `protobuf:"bytes,1,opt,name=public_key_file,json=publicKeyFile,proto3" json:"public_key_file,omitempty"`
	KeyId             string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Issuer            string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience          string                 `protobuf:"bytes,4,opt,name=audience,proto3" json:"audience,omitempty"`
	Subject           string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	MaxTokenTtl       string                 `protobuf:"bytes,6,opt,name=max_token_ttl,json=maxTokenTtl,proto3" json:"max_token_ttl,omitempty"`
	ClockSkew         string                 `protobuf:"bytes,7,opt,name=clock_skew,json=clockSkew,proto3" json:"clock_skew,omitempty"`
	AdditionalCallers []*InternalCallerProto `protobuf:"bytes,8,rep,name=additional_callers,json=additionalCallers,proto3" json:"additional_callers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InternalAuthProto) Reset() {
	*x = InternalAuthProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalAuthProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalAuthProto) ProtoMessage() {}

func (x *InternalAuthProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalAuthProto.ProtoReflect.Descriptor instead.
func (*InternalAuthProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *InternalAuthProto) GetPublicKeyFile() string {
	if x != nil {
		return x.PublicKeyFile
	}
	return ""
}

func (x *InternalAuthProto) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *InternalAuthProto) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *InternalAuthProto) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *InternalAuthProto) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *InternalAuthProto) GetMaxTokenTtl() string {
	if x != nil {
		return x.MaxTokenTtl
	}
	return ""
}

func (x *InternalAuthProto) GetClockSkew() string {
	if x != nil {
		return x.ClockSkew
	}
	return ""
}

func (x *InternalAuthProto) GetAdditionalCallers() []*InternalCallerProto {
	if x != nil {
		return x.AdditionalCallers
	}
	return nil
}

type InternalCallerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyFile string                 `protobuf:"bytes,1,opt,name=public_key_file,json=publicKeyFile,proto3" json:"public_key_file,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalCallerProto) Reset() {
	*x = InternalCallerProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalCallerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalCallerProto) ProtoMessage() {}

func (x *InternalCallerProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalCallerProto.ProtoReflect.Descriptor instead.
func (*InternalCallerProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *InternalCallerProto) GetPublicKeyFile() string {
	if x != nil {
		return x.PublicKeyFile
	}
	return ""
}

func (x *InternalCallerProto) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *InternalCallerProto) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *InternalCallerProto) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type ServiceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceProto) Reset() {
	*x = ServiceProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceProto) ProtoMessage() {}

func (x *ServiceProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceProto.ProtoReflect.Descriptor instead.
func (*ServiceProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *GRPCProto             `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerProto) Reset() {
	*x = ServerProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerProto) ProtoMessage() {}

func (x *ServerProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerProto.ProtoReflect.Descriptor instead.
func (*ServerProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *ServerProto) GetGrpc() *GRPCProto {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type GRPCProto struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Address                string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	MaxReceiveMessageBytes int32                  `protobuf:"varint,2,opt,name=max_receive_message_bytes,json=maxReceiveMessageBytes,proto3" json:"max_receive_message_bytes,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GRPCProto) Reset() {
	*x = GRPCProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCProto) ProtoMessage() {}

func (x *GRPCProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCProto.ProtoReflect.Descriptor instead.
func (*GRPCProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *GRPCProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GRPCProto) GetMaxReceiveMessageBytes() int32 {
	if x != nil {
		return x.MaxReceiveMessageBytes
	}
	return 0
}

type DataProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MysqlDsn       string                 `protobuf:"bytes,1,opt,name=mysql_dsn,json=mysqlDsn,proto3" json:"mysql_dsn,omitempty"`
	RedisAddr      string                 `protobuf:"bytes,2,opt,name=redis_addr,json=redisAddr,proto3" json:"redis_addr,omitempty"`
	RedisPassword  string                 `protobuf:"bytes,3,opt,name=redis_password,json=redisPassword,proto3" json:"redis_password,omitempty"`
	RedisDb        int32                  `protobuf:"varint,4,opt,name=redis_db,json=redisDb,proto3" json:"redis_db,omitempty"`
	RedisNamespace string                 `protobuf:"bytes,5,opt,name=redis_namespace,json=redisNamespace,proto3" json:"redis_namespace,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataProto) Reset() {
	*x = DataProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProto) ProtoMessage() {}

func (x *DataProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProto.ProtoReflect.Descriptor instead.
func (*DataProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *DataProto) GetMysqlDsn() string {
	if x != nil {
		return x.MysqlDsn
	}
	return ""
}

func (x *DataProto) GetRedisAddr() string {
	if x != nil {
		return x.RedisAddr
	}
	return ""
}

func (x *DataProto) GetRedisPassword() string {
	if x != nil {
		return x.RedisPassword
	}
	return ""
}

func (x *DataProto) GetRedisDb() int32 {
	if x != nil {
		return x.RedisDb
	}
	return 0
}

func (x *DataProto) GetRedisNamespace() string {
	if x != nil {
		return x.RedisNamespace
	}
	return ""
}

type StorageProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minio         *MinIOProto            `protobuf:"bytes,1,opt,name=minio,proto3" json:"minio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageProto) Reset() {
	*x = StorageProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageProto) ProtoMessage() {}

func (x *StorageProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageProto.ProtoReflect.Descriptor instead.
func (*StorageProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *StorageProto) GetMinio() *MinIOProto {
	if x != nil {
		return x.Minio
	}
	return nil
}

type MinIOProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AccessKey     string                 `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	SecretKey     string                 `protobuf:"bytes,3,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	Bucket        string                 `protobuf:"bytes,4,opt,name=bucket,proto3" json:"bucket,omitempty"`
	UseSsl        bool                   `protobuf:"varint,5,opt,name=use_ssl,json=useSsl,proto3" json:"use_ssl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinIOProto) Reset() {
	*x = MinIOProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinIOProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinIOProto) ProtoMessage() {}

func (x *MinIOProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinIOProto.ProtoReflect.Descriptor instead.
func (*MinIOProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *MinIOProto) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MinIOProto) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *MinIOProto) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

func (x *MinIOProto) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MinIOProto) GetUseSsl() bool {
	if x != nil {
		return x.UseSsl
	}
	return false
}

type RegistryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consul        *ConsulProto           `protobuf:"bytes,1,opt,name=consul,proto3" json:"consul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryProto) Reset() {
	*x = RegistryProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryProto) ProtoMessage() {}

func (x *RegistryProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryProto.ProtoReflect.Descriptor instead.
func (*RegistryProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *RegistryProto) GetConsul() *ConsulProto {
	if x != nil {
		return x.Consul
	}
	return nil
}

type ConsulProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Scheme        string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Datacenter    string                 `protobuf:"bytes,4,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ServiceId     string                 `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsulProto) Reset() {
	*x = ConsulProto{}
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsulProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsulProto) ProtoMessage() {}

func (x *ConsulProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_problem_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsulProto.ProtoReflect.Descriptor instead.
func (*ConsulProto) Descriptor() ([]byte, []int) {
	return file_services_problem_internal_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *ConsulProto) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConsulProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConsulProto) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ConsulProto) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *ConsulProto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConsulProto) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

var File_services_problem_internal_conf_conf_proto protoreflect.FileDescriptor

const file_services_problem_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	")services/problem/internal/conf/conf.proto\x12\fproblem.conf\"\xd6\x02\n" +
	"\tBootstrap\x124\n" +
	"\aservice\x18\x01 \x01(\v2\x1a.problem.conf.ServiceProtoR\aservice\x121\n" +
	"\x06server\x18\x02 \x01(\v2\x19.problem.conf.ServerProtoR\x06server\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.problem.conf.DataProtoR\x04data\x124\n" +
	"\astorage\x18\x04 \x01(\v2\x1a.problem.conf.StorageProtoR\astorage\x127\n" +
	"\bregistry\x18\x05 \x01(\v2\x1b.problem.conf.RegistryProtoR\bregistry\x12D\n" +
	"\rinternal_auth\x18\x06 \x01(\v2\x1f.problem.conf.InternalAuthProtoR\finternalAuth\"\xb5\x02\n" +
	"\x11InternalAuthProto\x12&\n" +
	"\x0fpublic_key_file\x18\x01 \x01(\tR\rpublicKeyFile\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x04 \x01(\tR\baudience\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\"\n" +
	"\rmax_token_ttl\x18\x06 \x01(\tR\vmaxTokenTtl\x12\x1d\n" +
	"\n" +
	"clock_skew\x18\a \x01(\tR\tclockSkew\x12P\n" +
	"\x12additional_callers\x18\b \x03(\v2!.problem.conf.InternalCallerProtoR\x11additionalCallers\"\x86\x01\n" +
	"\x13InternalCallerProto\x12&\n" +
	"\x0fpublic_key_file\x18\x01 \x01(\tR\rpublicKeyFile\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x04 \x01(\tR\asubject\"\"\n" +
	"\fServiceProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\vServerProto\x12+\n" +
	"\x04grpc\x18\x01 \x01(\v2\x17.problem.conf.GRPCProtoR\x04grpc\"`\n" +
	"\tGRPCProto\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x129\n" +
	"\x19max_receive_message_bytes\x18\x02 \x01(\x05R\x16maxReceiveMessageBytes\"\xb2\x01\n" +
	"\tDataProto\x12\x1b\n" +
	"\tmysql_dsn\x18\x01 \x01(\tR\bmysqlDsn\x12\x1d\n" +
	"\n" +
	"redis_addr\x18\x02 \x01(\tR\tredisAddr\x12%\n" +
	"\x0eredis_password\x18\x03 \x01(\tR\rredisPassword\x12\x19\n" +
	"\bredis_db\x18\x04 \x01(\x05R\aredisDb\x12'\n" +
	"\x0fredis_namespace\x18\x05 \x01(\tR\x0eredisNamespace\">\n" +
	"\fStorageProto\x12.\n" +
	"\x05minio\x18\x01 \x01(\v2\x18.problem.conf.MinIOProtoR\x05minio\"\x97\x01\n" +
	"\n" +
	"MinIOProto\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"access_key\x18\x02 \x01(\tR\taccessKey\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x03 \x01(\tR\tsecretKey\x12\x16\n" +
	"\x06bucket\x18\x04 \x01(\tR\x06bucket\x12\x17\n" +
	"\ause_ssl\x18\x05 \x01(\bR\x06useSsl\"B\n" +
	"\rRegistryProto\x121\n" +
	"\x06consul\x18\x01 \x01(\v2\x19.problem.conf.ConsulProtoR\x06consul\"\xae\x01\n" +
	"\vConsulProto\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x04 \x01(\tR\n" +
	"datacenter\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tR\tserviceIdBEZCgithub.com/viggggil/go_oj_agent/services/problem/internal/conf;confb\x06proto3"

var (
	file_services_problem_internal_conf_conf_proto_rawDescOnce sync.Once
	file_services_problem_internal_conf_conf_proto_rawDescData []byte
)

func file_services_problem_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_services_problem_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_services_problem_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_problem_internal_conf_conf_proto_rawDesc), len(file_services_problem_internal_conf_conf_proto_rawDesc)))
	})
	return file_services_problem_internal_conf_conf_proto_rawDescData
}

var file_services_problem_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_services_problem_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: problem.conf.Bootstrap
	(*InternalAuthProto)(nil),   // 1: problem.conf.InternalAuthProto
	(*InternalCallerProto)(nil), // 2: problem.conf.InternalCallerProto
	(*ServiceProto)(nil),        // 3: problem.conf.ServiceProto
	(*ServerProto)(nil),         // 4: problem.conf.ServerProto
	(*GRPCProto)(nil),           // 5: problem.conf.GRPCProto
	(*DataProto)(nil),           // 6: problem.conf.DataProto
	(*StorageProto)(nil),        // 7: problem.conf.StorageProto
	(*MinIOProto)(nil),          // 8: problem.conf.MinIOProto
	(*RegistryProto)(nil),       // 9: problem.conf.RegistryProto
	(*ConsulProto)(nil),         // 10: problem.conf.ConsulProto
}
var file_services_problem_internal_conf_conf_proto_depIdxs = []int32{
	3,  // 0: problem.conf.Bootstrap.service:type_name -> problem.conf.ServiceProto
	4,  // 1: problem.conf.Bootstrap.server:type_name -> problem.conf.ServerProto
	6,  // 2: problem.conf.Bootstrap.data:type_name -> problem.conf.DataProto
	7,  // 3: problem.conf.Bootstrap.storage:type_name -> problem.conf.StorageProto
	9,  // 4: problem.conf.Bootstrap.registry:type_name -> problem.conf.RegistryProto
	1,  // 5: problem.conf.Bootstrap.internal_auth:type_name -> problem.conf.InternalAuthProto
	2,  // 6: problem.conf.InternalAuthProto.additional_callers:type_name -> problem.conf.InternalCallerProto
	5,  // 7: problem.conf.ServerProto.grpc:type_name -> problem.conf.GRPCProto
	8,  // 8: problem.conf.StorageProto.minio:type_name -> problem.conf.MinIOProto
	10, // 9: problem.conf.RegistryProto.consul:type_name -> problem.conf.ConsulProto
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_services_problem_internal_conf_conf_proto_init() }
func file_services_problem_internal_conf_conf_proto_init() {
	if File_services_problem_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_problem_internal_conf_conf_proto_rawDesc), len(file_services_problem_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_problem_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_services_problem_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_services_problem_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_services_problem_internal_conf_conf_proto = out.File
	file_services_problem_internal_conf_conf_proto_goTypes = nil
	file_services_problem_internal_conf_conf_proto_depIdxs = nil
}
