// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/viggggil/go_oj_agent/services/contest/internal/biz"
	"github.com/viggggil/go_oj_agent/services/contest/internal/conf"
	"github.com/viggggil/go_oj_agent/services/contest/internal/server"
	"github.com/viggggil/go_oj_agent/services/contest/internal/service"
)

// Injectors from wire.go:

func initApp(config *conf.Bootstrap) (*App, func(), error) {
	v := server.NewMiddlewares()
	contestUsecase := biz.NewContestUsecase()
	contestService := service.NewContestService(contestUsecase)
	grpcServer, err := server.NewGRPCServer(config, v, contestService)
	if err != nil {
		return nil, nil, err
	}
	registrar := server.NewRegistrar(config)
	v2 := newApp(config, grpcServer, registrar)
	return v2, func() {
	}, nil
}
