// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package userv1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUserErrorReasonInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_INVALID_ARGUMENT.String() && e.Code == 400
}

func ErrorUserErrorReasonInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, UserErrorReason_USER_ERROR_REASON_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonInvalidCredential(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_INVALID_CREDENTIAL.String() && e.Code == 401
}

func ErrorUserErrorReasonInvalidCredential(format string, args ...interface{}) *errors.Error {
	return errors.New(401, UserErrorReason_USER_ERROR_REASON_INVALID_CREDENTIAL.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorUserErrorReasonAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, UserErrorReason_USER_ERROR_REASON_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_NOT_FOUND.String() && e.Code == 404
}

func ErrorUserErrorReasonNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, UserErrorReason_USER_ERROR_REASON_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonAdminAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_ADMIN_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorUserErrorReasonAdminAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, UserErrorReason_USER_ERROR_REASON_ADMIN_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonInactive(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_INACTIVE.String() && e.Code == 403
}

func ErrorUserErrorReasonInactive(format string, args ...interface{}) *errors.Error {
	return errors.New(403, UserErrorReason_USER_ERROR_REASON_INACTIVE.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonPermissionDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_PERMISSION_DENIED.String() && e.Code == 403
}

func ErrorUserErrorReasonPermissionDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, UserErrorReason_USER_ERROR_REASON_PERMISSION_DENIED.String(), fmt.Sprintf(format, args...))
}

func IsUserErrorReasonRefreshTokenDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == UserErrorReason_USER_ERROR_REASON_REFRESH_TOKEN_DENIED.String() && e.Code == 401
}

func ErrorUserErrorReasonRefreshTokenDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(401, UserErrorReason_USER_ERROR_REASON_REFRESH_TOKEN_DENIED.String(), fmt.Sprintf(format, args...))
}
