service:
  name: contest-service
server:
  grpc:
    address: ":9005"
    max_receive_message_bytes: 35651584
data:
  mysql_dsn: "root:local-root-password@tcp(127.0.0.1:3306)/oj_contest?parseTime=true"
registry:
  consul:
    enabled: false
    address: "127.0.0.1:8500"
    scheme: "http"
    datacenter: ""
    token: ""
    service_id: ""
internal_auth:
  public_key_file: ""
  key_id: "contest-internal-2026-09"
  issuer: "go-oj-contest"
  audience: "contest-service"
  subject: ""
  max_token_ttl: "30s"
  clock_skew: "5s"
