// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/judge/v1/judge.proto

package judgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_UNSPECIFIED WorkerStatus = 0
	WorkerStatus_WORKER_STATUS_IDLE        WorkerStatus = 1
	WorkerStatus_WORKER_STATUS_BUSY        WorkerStatus = 2
	WorkerStatus_WORKER_STATUS_DRAINING    WorkerStatus = 3
	WorkerStatus_WORKER_STATUS_OFFLINE     WorkerStatus = 4
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "WORKER_STATUS_UNSPECIFIED",
		1: "WORKER_STATUS_IDLE",
		2: "WORKER_STATUS_BUSY",
		3: "WORKER_STATUS_DRAINING",
		4: "WORKER_STATUS_OFFLINE",
	}
	WorkerStatus_value = map[string]int32{
		"WORKER_STATUS_UNSPECIFIED": 0,
		"WORKER_STATUS_IDLE":        1,
		"WORKER_STATUS_BUSY":        2,
		"WORKER_STATUS_DRAINING":    3,
		"WORKER_STATUS_OFFLINE":     4,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_judge_v1_judge_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_api_judge_v1_judge_proto_enumTypes[0]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_judge_v1_judge_proto_rawDescGZIP(), []int{0}
}

type JudgeVerdict int32

const (
	JudgeVerdict_JUDGE_VERDICT_UNSPECIFIED JudgeVerdict = 0
	JudgeVerdict_JUDGE_VERDICT_AC          JudgeVerdict = 1
	JudgeVerdict_JUDGE_VERDICT_WA          JudgeVerdict = 2
	JudgeVerdict_JUDGE_VERDICT_TLE         JudgeVerdict = 3
	JudgeVerdict_JUDGE_VERDICT_MLE         JudgeVerdict = 4
	JudgeVerdict_JUDGE_VERDICT_RE          JudgeVerdict = 5
	JudgeVerdict_JUDGE_VERDICT_CE          JudgeVerdict = 6
)

// Enum value maps for JudgeVerdict.
var (
	JudgeVerdict_name = map[int32]string{
		0: "JUDGE_VERDICT_UNSPECIFIED",
		1: "JUDGE_VERDICT_AC",
		2: "JUDGE_VERDICT_WA",
		3: "JUDGE_VERDICT_TLE",
		4: "JUDGE_VERDICT_MLE",
		5: "JUDGE_VERDICT_RE",
		6: "JUDGE_VERDICT_CE",
	}
	JudgeVerdict_value = map[string]int32{
		"JUDGE_VERDICT_UNSPECIFIED": 0,
		"JUDGE_VERDICT_AC":          1,
		"JUDGE_VERDICT_WA":          2,
		"JUDGE_VERDICT_TLE":         3,
		"JUDGE_VERDICT_MLE":         4,
		"JUDGE_VERDICT_RE":          5,
		"JUDGE_VERDICT_CE":          6,
	}
)

func (x JudgeVerdict) Enum() *JudgeVerdict {
	p := new(JudgeVerdict)
	*p = x
	return p
}

func (x JudgeVerdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JudgeVerdict) Descriptor() protoreflect.EnumDescriptor {
	return file_api_judge_v1_judge_proto_enumTypes[1].Descriptor()
}

func (JudgeVerdict) Type() protoreflect.EnumType {
	return &file_api_judge_v1_judge_proto_enumTypes[1]
}

func (x JudgeVerdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JudgeVerdict.Descriptor instead.
func (JudgeVerdict) EnumDescriptor() ([]byte, []int) {
	return file_api_judge_v1_judge_proto_rawDescGZIP(), []int{1}
}

type JudgeCaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseNo        int32                  `protobuf:"varint,1,opt,name=case_no,json=caseNo,proto3" json:"case_no,omitempty"`
	Verdict       JudgeVerdict           `protobuf:"varint,2,opt,name=verdict,proto3,enum=judge.v1.JudgeVerdict" json:"verdict,omitempty"`
	TimeMs        int32                  `protobuf:"varint,3,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	MemoryKb      int32                  `protobuf:"varint,4,opt,name=memory_kb,json=memoryKb,proto3" json:"memory_kb,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeCaseResult) Reset() {
	*x = JudgeCaseResult{}
	mi := &file_api_judge_v1_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeCaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeCaseResult) ProtoMessage() {}

func (x *JudgeCaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_judge_v1_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeCaseResult.ProtoReflect.Descriptor instead.
func (*JudgeCaseResult) Descriptor() ([]byte, []int) {
	return file_api_judge_v1_judge_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeCaseResult) GetCaseNo() int32 {
	if x != nil {
		return x.CaseNo
	}
	return 0
}

func (x *JudgeCaseResult) GetVerdict() JudgeVerdict {
	if x != nil {
		return x.Verdict
	}
	return JudgeVerdict_JUDGE_VERDICT_UNSPECIFIED
}

func (x *JudgeCaseResult) GetTimeMs() int32 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *JudgeCaseResult) GetMemoryKb() int32 {
	if x != nil {
		return x.MemoryKb
	}
	return 0
}

func (x *JudgeCaseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JudgeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  int64                  `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Verdict       JudgeVerdict           `protobuf:"varint,2,opt,name=verdict,proto3,enum=judge.v1.JudgeVerdict" json:"verdict,omitempty"`
	TimeMs        int32                  `protobuf:"varint,3,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	MemoryKb      int32                  `protobuf:"varint,4,opt,name=memory_kb,json=memoryKb,proto3" json:"memory_kb,omitempty"`
	CaseResults   []*JudgeCaseResult     `protobuf:"bytes,5,rep,name=case_results,json=caseResults,proto3" json:"case_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeResult) Reset() {
	*x = JudgeResult{}
	mi := &file_api_judge_v1_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeResult) ProtoMessage() {}

func (x *JudgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_judge_v1_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeResult.ProtoReflect.Descriptor instead.
func (*JudgeResult) Descriptor() ([]byte, []int) {
	return file_api_judge_v1_judge_proto_rawDescGZIP(), []int{1}
}

func (x *JudgeResult) GetSubmissionId() int64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *JudgeResult) GetVerdict() JudgeVerdict {
	if x != nil {
		return x.Verdict
	}
	return JudgeVerdict_JUDGE_VERDICT_UNSPECIFIED
}

func (x *JudgeResult) GetTimeMs() int32 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *JudgeResult) GetMemoryKb() int32 {
	if x != nil {
		return x.MemoryKb
	}
	return 0
}

func (x *JudgeResult) GetCaseResults() []*JudgeCaseResult {
	if x != nil {
		return x.CaseResults
	}
	return nil
}

type GetWorkerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerStatusRequest) Reset() {
	*x = GetWorkerStatusRequest{}
	mi := &file_api_judge_v1_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerStatusRequest) ProtoMessage() {}

func (x *GetWorkerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_judge_v1_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_judge_v1_judge_proto_rawDescGZIP(), []int{2}
}

func (x *GetWorkerStatusRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetWorkerStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status             WorkerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=judge.v1.WorkerStatus" json:"status,omitempty"`
	SupportedLanguages []string               `protobuf:"bytes,3,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages,omitempty"`
	RunningTasks       int32                  `protobuf:"varint,4,opt,name=running_tasks,json=runningTasks,proto3" json:"running_tasks,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWorkerStatusResponse) Reset() {
	*x = GetWorkerStatusResponse{}
	mi := &file_api_judge_v1_judge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerStatusResponse) ProtoMessage() {}

func (x *GetWorkerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_judge_v1_judge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_judge_v1_judge_proto_rawDescGZIP(), []int{3}
}

func (x *GetWorkerStatusResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetWorkerStatusResponse) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNSPECIFIED
}

func (x *GetWorkerStatusResponse) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

func (x *GetWorkerStatusResponse) GetRunningTasks() int32 {
	if x != nil {
		return x.RunningTasks
	}
	return 0
}

var File_api_judge_v1_judge_proto protoreflect.FileDescriptor

const file_api_judge_v1_judge_proto_rawDesc = "" +
	"\n" +
	"\x18api/judge/v1/judge.proto\x12\bjudge.v1\"\xac\x01\n" +
	"\x0fJudgeCaseResult\x12\x17\n" +
	"\acase_no\x18\x01 \x01(\x05R\x06caseNo\x120\n" +
	"\averdict\x18\x02 \x01(\x0e2\x16.judge.v1.JudgeVerdictR\averdict\x12\x17\n" +
	"\atime_ms\x18\x03 \x01(\x05R\x06timeMs\x12\x1b\n" +
	"\tmemory_kb\x18\x04 \x01(\x05R\bmemoryKb\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xd8\x01\n" +
	"\vJudgeResult\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\x03R\fsubmissionId\x120\n" +
	"\averdict\x18\x02 \x01(\x0e2\x16.judge.v1.JudgeVerdictR\averdict\x12\x17\n" +
	"\atime_ms\x18\x03 \x01(\x05R\x06timeMs\x12\x1b\n" +
	"\tmemory_kb\x18\x04 \x01(\x05R\bmemoryKb\x12<\n" +
	"\fcase_results\x18\x05 \x03(\v2\x19.judge.v1.JudgeCaseResultR\vcaseResults\"5\n" +
	"\x16GetWorkerStatusRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\xbc\x01\n" +
	"\x17GetWorkerStatusResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.judge.v1.WorkerStatusR\x06status\x12/\n" +
	"\x13supported_languages\x18\x03 \x03(\tR\x12supportedLanguages\x12#\n" +
	"\rrunning_tasks\x18\x04 \x01(\x05R\frunningTasks*\x94\x01\n" +
	"\fWorkerStatus\x12\x1d\n" +
	"\x19WORKER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12WORKER_STATUS_IDLE\x10\x01\x12\x16\n" +
	"\x12WORKER_STATUS_BUSY\x10\x02\x12\x1a\n" +
	"\x16WORKER_STATUS_DRAINING\x10\x03\x12\x19\n" +
	"\x15WORKER_STATUS_OFFLINE\x10\x04*\xb3\x01\n" +
	"\fJudgeVerdict\x12\x1d\n" +
	"\x19JUDGE_VERDICT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JUDGE_VERDICT_AC\x10\x01\x12\x14\n" +
	"\x10JUDGE_VERDICT_WA\x10\x02\x12\x15\n" +
	"\x11JUDGE_VERDICT_TLE\x10\x03\x12\x15\n" +
	"\x11JUDGE_VERDICT_MLE\x10\x04\x12\x14\n" +
	"\x10JUDGE_VERDICT_RE\x10\x05\x12\x14\n" +
	"\x10JUDGE_VERDICT_CE\x10\x062k\n" +
	"\x11JudgeAdminService\x12V\n" +
	"\x0fGetWorkerStatus\x12 .judge.v1.GetWorkerStatusRequest\x1a!.judge.v1.GetWorkerStatusResponseB6Z4github.com/viggggil/go_oj_agent/api/judge/v1;judgev1b\x06proto3"

var (
	file_api_judge_v1_judge_proto_rawDescOnce sync.Once
	file_api_judge_v1_judge_proto_rawDescData []byte
)

func file_api_judge_v1_judge_proto_rawDescGZIP() []byte {
	file_api_judge_v1_judge_proto_rawDescOnce.Do(func() {
		file_api_judge_v1_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_judge_v1_judge_proto_rawDesc), len(file_api_judge_v1_judge_proto_rawDesc)))
	})
	return file_api_judge_v1_judge_proto_rawDescData
}

var file_api_judge_v1_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_judge_v1_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_judge_v1_judge_proto_goTypes = []any{
	(WorkerStatus)(0),               // 0: judge.v1.WorkerStatus
	(JudgeVerdict)(0),               // 1: judge.v1.JudgeVerdict
	(*JudgeCaseResult)(nil),         // 2: judge.v1.JudgeCaseResult
	(*JudgeResult)(nil),             // 3: judge.v1.JudgeResult
	(*GetWorkerStatusRequest)(nil),  // 4: judge.v1.GetWorkerStatusRequest
	(*GetWorkerStatusResponse)(nil), // 5: judge.v1.GetWorkerStatusResponse
}
var file_api_judge_v1_judge_proto_depIdxs = []int32{
	1, // 0: judge.v1.JudgeCaseResult.verdict:type_name -> judge.v1.JudgeVerdict
	1, // 1: judge.v1.JudgeResult.verdict:type_name -> judge.v1.JudgeVerdict
	2, // 2: judge.v1.JudgeResult.case_results:type_name -> judge.v1.JudgeCaseResult
	0, // 3: judge.v1.GetWorkerStatusResponse.status:type_name -> judge.v1.WorkerStatus
	4, // 4: judge.v1.JudgeAdminService.GetWorkerStatus:input_type -> judge.v1.GetWorkerStatusRequest
	5, // 5: judge.v1.JudgeAdminService.GetWorkerStatus:output_type -> judge.v1.GetWorkerStatusResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_judge_v1_judge_proto_init() }
func file_api_judge_v1_judge_proto_init() {
	if File_api_judge_v1_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_judge_v1_judge_proto_rawDesc), len(file_api_judge_v1_judge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_judge_v1_judge_proto_goTypes,
		DependencyIndexes: file_api_judge_v1_judge_proto_depIdxs,
		EnumInfos:         file_api_judge_v1_judge_proto_enumTypes,
		MessageInfos:      file_api_judge_v1_judge_proto_msgTypes,
	}.Build()
	File_api_judge_v1_judge_proto = out.File
	file_api_judge_v1_judge_proto_goTypes = nil
	file_api_judge_v1_judge_proto_depIdxs = nil
}
