// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: gateway/v1/gateway.proto

package gatewayv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *APIResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type APIError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIError) Reset() {
	*x = APIError{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIError) ProtoMessage() {}

func (x *APIError) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIError.ProtoReflect.Descriptor instead.
func (*APIError) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *APIError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *APIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APIError) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Roles         []string               `protobuf:"bytes,5,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *UserSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSummary) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserSummary) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type RegisterHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHTTPRequest) Reset() {
	*x = RegisterHTTPRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHTTPRequest) ProtoMessage() {}

func (x *RegisterHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHTTPRequest.ProtoReflect.Descriptor instead.
func (*RegisterHTTPRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterHTTPRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterHTTPRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterHTTPRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHTTPResponse) Reset() {
	*x = RegisterHTTPResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHTTPResponse) ProtoMessage() {}

func (x *RegisterHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHTTPResponse.ProtoReflect.Descriptor instead.
func (*RegisterHTTPResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterHTTPResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginHTTPRequest) Reset() {
	*x = LoginHTTPRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginHTTPRequest) ProtoMessage() {}

func (x *LoginHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginHTTPRequest.ProtoReflect.Descriptor instead.
func (*LoginHTTPRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *LoginHTTPRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginHTTPRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokenHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenHTTPResponse) Reset() {
	*x = TokenHTTPResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenHTTPResponse) ProtoMessage() {}

func (x *TokenHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenHTTPResponse.ProtoReflect.Descriptor instead.
func (*TokenHTTPResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *TokenHTTPResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenHTTPResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenHTTPResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type RefreshTokenHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenHTTPRequest) Reset() {
	*x = RefreshTokenHTTPRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenHTTPRequest) ProtoMessage() {}

func (x *RefreshTokenHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenHTTPRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenHTTPRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenHTTPRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetCurrentUserHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserHTTPResponse) Reset() {
	*x = GetCurrentUserHTTPResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserHTTPResponse) ProtoMessage() {}

func (x *GetCurrentUserHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserHTTPResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserHTTPResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *GetCurrentUserHTTPResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserSummary           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserHTTPResponse) Reset() {
	*x = GetUserHTTPResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserHTTPResponse) ProtoMessage() {}

func (x *GetUserHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserHTTPResponse.ProtoReflect.Descriptor instead.
func (*GetUserHTTPResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserHTTPResponse) GetUser() *UserSummary {
	if x != nil {
		return x.User
	}
	return nil
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\x1a\x17validate/validate.proto\",\n" +
	"\vAPIResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"W\n" +
	"\bAPIError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"}\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05roles\x18\x05 \x03(\tR\x05roles\"\x85\x01\n" +
	"\x13RegisterHTTPRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\busername\x12 \n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x18\xff\x01`\x01R\x05email\x12%\n" +
	"\bpassword\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\b(HR\bpassword\"C\n" +
	"\x14RegisterHTTPResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.gateway.v1.UserSummaryR\x04user\"_\n" +
	"\x10LoginHTTPRequest\x12$\n" +
	"\aaccount\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\aaccount\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01(HR\bpassword\"z\n" +
	"\x11TokenHTTPResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"J\n" +
	"\x17RefreshTokenHTTPRequest\x12/\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\x80\x10R\frefreshToken\"I\n" +
	"\x1aGetCurrentUserHTTPResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.gateway.v1.UserSummaryR\x04user\"B\n" +
	"\x13GetUserHTTPResponse\x12+\n" +
	"\x04user\x18\x01 \x01(\v2\x17.gateway.v1.UserSummaryR\x04userB:Z8github.com/viggggil/go_oj_agent/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*APIResponse)(nil),                // 0: gateway.v1.APIResponse
	(*APIError)(nil),                   // 1: gateway.v1.APIError
	(*UserSummary)(nil),                // 2: gateway.v1.UserSummary
	(*RegisterHTTPRequest)(nil),        // 3: gateway.v1.RegisterHTTPRequest
	(*RegisterHTTPResponse)(nil),       // 4: gateway.v1.RegisterHTTPResponse
	(*LoginHTTPRequest)(nil),           // 5: gateway.v1.LoginHTTPRequest
	(*TokenHTTPResponse)(nil),          // 6: gateway.v1.TokenHTTPResponse
	(*RefreshTokenHTTPRequest)(nil),    // 7: gateway.v1.RefreshTokenHTTPRequest
	(*GetCurrentUserHTTPResponse)(nil), // 8: gateway.v1.GetCurrentUserHTTPResponse
	(*GetUserHTTPResponse)(nil),        // 9: gateway.v1.GetUserHTTPResponse
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	2, // 0: gateway.v1.RegisterHTTPResponse.user:type_name -> gateway.v1.UserSummary
	2, // 1: gateway.v1.GetCurrentUserHTTPResponse.user:type_name -> gateway.v1.UserSummary
	2, // 2: gateway.v1.GetUserHTTPResponse.user:type_name -> gateway.v1.UserSummary
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
