// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/viggggil/go_oj_agent/services/user/internal/biz"
	"github.com/viggggil/go_oj_agent/services/user/internal/conf"
	"github.com/viggggil/go_oj_agent/services/user/internal/data"
	"github.com/viggggil/go_oj_agent/services/user/internal/security"
	"github.com/viggggil/go_oj_agent/services/user/internal/server"
	"github.com/viggggil/go_oj_agent/services/user/internal/service"
)

// Injectors from wire.go:

func initApp(bc *conf.Bootstrap) (*kratos.App, func(), error) {
	v := server.NewMiddlewares()
	db, cleanup, err := data.NewMySQLDB(bc)
	if err != nil {
		return nil, nil, err
	}
	storeSet := data.NewStoreSet(db)
	hmacTokenManager, err := security.NewHMACTokenManagerFromConfig(bc)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := data.NewRedisClient(bc)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisRefreshTokenStore := data.NewRefreshTokenStore(client, bc)
	userUsecase := biz.NewUserUsecaseFromConfig(bc, storeSet, storeSet, hmacTokenManager, redisRefreshTokenStore)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(bc, v, userService)
	registrar := server.NewRegistrar(bc)
	app := newApp(bc, grpcServer, registrar)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
