// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"github.com/viggggil/go_oj_agent/services/user/internal/biz"
	"github.com/viggggil/go_oj_agent/services/user/internal/conf"
	"github.com/viggggil/go_oj_agent/services/user/internal/data"
	"github.com/viggggil/go_oj_agent/services/user/internal/server"
	"github.com/viggggil/go_oj_agent/services/user/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, func(), error) {
	config, err := conf.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	v := server.NewMiddlewares()
	db, cleanup, err := data.NewMySQLDB(config)
	if err != nil {
		return nil, nil, err
	}
	storeSet := data.NewStoreSet(db)
	hmacTokenManager, err := biz.NewHMACTokenManagerFromConfig(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, cleanup2, err := data.NewRedisClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisRefreshTokenStore := data.NewRefreshTokenStore(client, config)
	userUsecase := biz.NewUserUsecaseFromConfig(config, storeSet, storeSet, hmacTokenManager, redisRefreshTokenStore)
	userService := service.NewUserService(userUsecase)
	grpcServer := server.NewGRPCServer(config, v, userService)
	registry := conf.NewRegistry(config)
	consulRegistry := server.NewRegistrar(registry)
	app := newApp(config, grpcServer, consulRegistry)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
