// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/contest/v1/contest.proto

package contestv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	v1 "github.com/viggggil/go_oj_agent/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContestStatus int32

const (
	ContestStatus_CONTEST_STATUS_UNSPECIFIED ContestStatus = 0
	ContestStatus_CONTEST_STATUS_DRAFT       ContestStatus = 1
	ContestStatus_CONTEST_STATUS_RUNNING     ContestStatus = 2
	ContestStatus_CONTEST_STATUS_ENDED       ContestStatus = 3
)

// Enum value maps for ContestStatus.
var (
	ContestStatus_name = map[int32]string{
		0: "CONTEST_STATUS_UNSPECIFIED",
		1: "CONTEST_STATUS_DRAFT",
		2: "CONTEST_STATUS_RUNNING",
		3: "CONTEST_STATUS_ENDED",
	}
	ContestStatus_value = map[string]int32{
		"CONTEST_STATUS_UNSPECIFIED": 0,
		"CONTEST_STATUS_DRAFT":       1,
		"CONTEST_STATUS_RUNNING":     2,
		"CONTEST_STATUS_ENDED":       3,
	}
)

func (x ContestStatus) Enum() *ContestStatus {
	p := new(ContestStatus)
	*p = x
	return p
}

func (x ContestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_contest_v1_contest_proto_enumTypes[0].Descriptor()
}

func (ContestStatus) Type() protoreflect.EnumType {
	return &file_api_contest_v1_contest_proto_enumTypes[0]
}

func (x ContestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContestStatus.Descriptor instead.
func (ContestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{0}
}

type ContestProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProblemId     int64                  `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestProblem) Reset() {
	*x = ContestProblem{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestProblem) ProtoMessage() {}

func (x *ContestProblem) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestProblem.ProtoReflect.Descriptor instead.
func (*ContestProblem) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{0}
}

func (x *ContestProblem) GetProblemId() int64 {
	if x != nil {
		return x.ProblemId
	}
	return 0
}

func (x *ContestProblem) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *ContestProblem) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Contest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        ContestStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=contest.v1.ContestStatus" json:"status,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Problems      []*ContestProblem      `protobuf:"bytes,9,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contest) Reset() {
	*x = Contest{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contest) ProtoMessage() {}

func (x *Contest) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contest.ProtoReflect.Descriptor instead.
func (*Contest) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{1}
}

func (x *Contest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Contest) GetStatus() ContestStatus {
	if x != nil {
		return x.Status
	}
	return ContestStatus_CONTEST_STATUS_UNSPECIFIED
}

func (x *Contest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Contest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Contest) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Contest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Contest) GetProblems() []*ContestProblem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type ContestSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        ContestStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=contest.v1.ContestStatus" json:"status,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestSummary) Reset() {
	*x = ContestSummary{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestSummary) ProtoMessage() {}

func (x *ContestSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestSummary.ProtoReflect.Descriptor instead.
func (*ContestSummary) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{2}
}

func (x *ContestSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContestSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContestSummary) GetStatus() ContestStatus {
	if x != nil {
		return x.Status
	}
	return ContestStatus_CONTEST_STATUS_UNSPECIFIED
}

func (x *ContestSummary) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *ContestSummary) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Penalty       int64                  `protobuf:"varint,4,opt,name=penalty,proto3" json:"penalty,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,5,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LeaderboardEntry) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetPenalty() int64 {
	if x != nil {
		return x.Penalty
	}
	return 0
}

func (x *LeaderboardEntry) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

type GetContestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     int64                  `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestRequest) Reset() {
	*x = GetContestRequest{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestRequest) ProtoMessage() {}

func (x *GetContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestRequest.ProtoReflect.Descriptor instead.
func (*GetContestRequest) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{4}
}

func (x *GetContestRequest) GetContestId() int64 {
	if x != nil {
		return x.ContestId
	}
	return 0
}

type GetContestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contest       *Contest               `protobuf:"bytes,1,opt,name=contest,proto3" json:"contest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContestReply) Reset() {
	*x = GetContestReply{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContestReply) ProtoMessage() {}

func (x *GetContestReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContestReply.ProtoReflect.Descriptor instead.
func (*GetContestReply) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{5}
}

func (x *GetContestReply) GetContest() *Contest {
	if x != nil {
		return x.Contest
	}
	return nil
}

// ContestUpdate is intentionally a complete replacement, not a patch. The
// service rejects updates once the contest has started.
type ContestUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Problems      []*ContestProblem      `protobuf:"bytes,4,rep,name=problems,proto3" json:"problems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContestUpdate) Reset() {
	*x = ContestUpdate{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContestUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContestUpdate) ProtoMessage() {}

func (x *ContestUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContestUpdate.ProtoReflect.Descriptor instead.
func (*ContestUpdate) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{6}
}

func (x *ContestUpdate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContestUpdate) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *ContestUpdate) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *ContestUpdate) GetProblems() []*ContestProblem {
	if x != nil {
		return x.Problems
	}
	return nil
}

type UpdateContestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     int64                  `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Contest       *ContestUpdate         `protobuf:"bytes,2,opt,name=contest,proto3" json:"contest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContestRequest) Reset() {
	*x = UpdateContestRequest{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContestRequest) ProtoMessage() {}

func (x *UpdateContestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContestRequest.ProtoReflect.Descriptor instead.
func (*UpdateContestRequest) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateContestRequest) GetContestId() int64 {
	if x != nil {
		return x.ContestId
	}
	return 0
}

func (x *UpdateContestRequest) GetContest() *ContestUpdate {
	if x != nil {
		return x.Contest
	}
	return nil
}

type UpdateContestReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contest       *Contest               `protobuf:"bytes,1,opt,name=contest,proto3" json:"contest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContestReply) Reset() {
	*x = UpdateContestReply{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContestReply) ProtoMessage() {}

func (x *UpdateContestReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContestReply.ProtoReflect.Descriptor instead.
func (*UpdateContestReply) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateContestReply) GetContest() *Contest {
	if x != nil {
		return x.Contest
	}
	return nil
}

type ListContestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Status        ContestStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=contest.v1.ContestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContestsRequest) Reset() {
	*x = ListContestsRequest{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContestsRequest) ProtoMessage() {}

func (x *ListContestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContestsRequest.ProtoReflect.Descriptor instead.
func (*ListContestsRequest) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{9}
}

func (x *ListContestsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListContestsRequest) GetStatus() ContestStatus {
	if x != nil {
		return x.Status
	}
	return ContestStatus_CONTEST_STATUS_UNSPECIFIED
}

type ListContestsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContestSummary      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContestsReply) Reset() {
	*x = ListContestsReply{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContestsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContestsReply) ProtoMessage() {}

func (x *ListContestsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContestsReply.ProtoReflect.Descriptor instead.
func (*ListContestsReply) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{10}
}

func (x *ListContestsReply) GetItems() []*ContestSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListContestsReply) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetLeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContestId     int64                  `protobuf:"varint,1,opt,name=contest_id,json=contestId,proto3" json:"contest_id,omitempty"`
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardRequest) Reset() {
	*x = GetLeaderboardRequest{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardRequest) ProtoMessage() {}

func (x *GetLeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardRequest.ProtoReflect.Descriptor instead.
func (*GetLeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{11}
}

func (x *GetLeaderboardRequest) GetContestId() int64 {
	if x != nil {
		return x.ContestId
	}
	return 0
}

func (x *GetLeaderboardRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetLeaderboardReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LeaderboardEntry    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLeaderboardReply) Reset() {
	*x = GetLeaderboardReply{}
	mi := &file_api_contest_v1_contest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLeaderboardReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLeaderboardReply) ProtoMessage() {}

func (x *GetLeaderboardReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_contest_v1_contest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLeaderboardReply.ProtoReflect.Descriptor instead.
func (*GetLeaderboardReply) Descriptor() ([]byte, []int) {
	return file_api_contest_v1_contest_proto_rawDescGZIP(), []int{12}
}

func (x *GetLeaderboardReply) GetItems() []*LeaderboardEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetLeaderboardReply) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_api_contest_v1_contest_proto protoreflect.FileDescriptor

const file_api_contest_v1_contest_proto_rawDesc = "" +
	"\n" +
	"\x1capi/contest/v1/contest.proto\x12\n" +
	"contest.v1\x1a\x1aapi/common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x7f\n" +
	"\x0eContestProblem\x12&\n" +
	"\n" +
	"problem_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tproblemId\x12&\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\tsortOrder\x12\x1d\n" +
	"\x05score\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x05score\"\x99\x03\n" +
	"\aContest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.contest.v1.ContestStatusR\x06status\x125\n" +
	"\bstart_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\x03R\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\bproblems\x18\t \x03(\v2\x1a.contest.v1.ContestProblemR\bproblems\"\xd3\x01\n" +
	"\x0eContestSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.contest.v1.ContestStatusR\x06status\x125\n" +
	"\bstart_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"\x96\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x18\n" +
	"\apenalty\x18\x04 \x01(\x03R\apenalty\x12%\n" +
	"\x0eaccepted_count\x18\x05 \x01(\x05R\racceptedCount\";\n" +
	"\x11GetContestRequest\x12&\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcontestId\"@\n" +
	"\x0fGetContestReply\x12-\n" +
	"\acontest\x18\x01 \x01(\v2\x13.contest.v1.ContestR\acontest\"\xf3\x01\n" +
	"\rContestUpdate\x12 \n" +
	"\x05title\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x05title\x12?\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\astartAt\x12;\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\x05endAt\x12B\n" +
	"\bproblems\x18\x04 \x03(\v2\x1a.contest.v1.ContestProblemB\n" +
	"\xfaB\a\x92\x01\x04\b\x01\x10dR\bproblems\"}\n" +
	"\x14UpdateContestRequest\x12&\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcontestId\x12=\n" +
	"\acontest\x18\x02 \x01(\v2\x19.contest.v1.ContestUpdateB\b\xfaB\x05\x8a\x01\x02\x10\x01R\acontest\"C\n" +
	"\x12UpdateContestReply\x12-\n" +
	"\acontest\x18\x01 \x01(\v2\x13.contest.v1.ContestR\acontest\"\x88\x01\n" +
	"\x13ListContestsRequest\x124\n" +
	"\x04page\x18\x01 \x01(\v2\x16.common.v1.PageRequestB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04page\x12;\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.contest.v1.ContestStatusB\b\xfaB\x05\x82\x01\x02\x10\x01R\x06status\"r\n" +
	"\x11ListContestsReply\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.contest.v1.ContestSummaryR\x05items\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page\"u\n" +
	"\x15GetLeaderboardRequest\x12&\n" +
	"\n" +
	"contest_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcontestId\x124\n" +
	"\x04page\x18\x02 \x01(\v2\x16.common.v1.PageRequestB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04page\"v\n" +
	"\x13GetLeaderboardReply\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.contest.v1.LeaderboardEntryR\x05items\x12+\n" +
	"\x04page\x18\x02 \x01(\v2\x17.common.v1.PageResponseR\x04page*\x7f\n" +
	"\rContestStatus\x12\x1e\n" +
	"\x1aCONTEST_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CONTEST_STATUS_DRAFT\x10\x01\x12\x1a\n" +
	"\x16CONTEST_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14CONTEST_STATUS_ENDED\x10\x032\xd3\x02\n" +
	"\x0eContestService\x12H\n" +
	"\n" +
	"GetContest\x12\x1d.contest.v1.GetContestRequest\x1a\x1b.contest.v1.GetContestReply\x12N\n" +
	"\fListContests\x12\x1f.contest.v1.ListContestsRequest\x1a\x1d.contest.v1.ListContestsReply\x12Q\n" +
	"\rUpdateContest\x12 .contest.v1.UpdateContestRequest\x1a\x1e.contest.v1.UpdateContestReply\x12T\n" +
	"\x0eGetLeaderboard\x12!.contest.v1.GetLeaderboardRequest\x1a\x1f.contest.v1.GetLeaderboardReplyB:Z8github.com/viggggil/go_oj_agent/api/contest/v1;contestv1b\x06proto3"

var (
	file_api_contest_v1_contest_proto_rawDescOnce sync.Once
	file_api_contest_v1_contest_proto_rawDescData []byte
)

func file_api_contest_v1_contest_proto_rawDescGZIP() []byte {
	file_api_contest_v1_contest_proto_rawDescOnce.Do(func() {
		file_api_contest_v1_contest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_contest_v1_contest_proto_rawDesc), len(file_api_contest_v1_contest_proto_rawDesc)))
	})
	return file_api_contest_v1_contest_proto_rawDescData
}

var file_api_contest_v1_contest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_contest_v1_contest_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_contest_v1_contest_proto_goTypes = []any{
	(ContestStatus)(0),            // 0: contest.v1.ContestStatus
	(*ContestProblem)(nil),        // 1: contest.v1.ContestProblem
	(*Contest)(nil),               // 2: contest.v1.Contest
	(*ContestSummary)(nil),        // 3: contest.v1.ContestSummary
	(*LeaderboardEntry)(nil),      // 4: contest.v1.LeaderboardEntry
	(*GetContestRequest)(nil),     // 5: contest.v1.GetContestRequest
	(*GetContestReply)(nil),       // 6: contest.v1.GetContestReply
	(*ContestUpdate)(nil),         // 7: contest.v1.ContestUpdate
	(*UpdateContestRequest)(nil),  // 8: contest.v1.UpdateContestRequest
	(*UpdateContestReply)(nil),    // 9: contest.v1.UpdateContestReply
	(*ListContestsRequest)(nil),   // 10: contest.v1.ListContestsRequest
	(*ListContestsReply)(nil),     // 11: contest.v1.ListContestsReply
	(*GetLeaderboardRequest)(nil), // 12: contest.v1.GetLeaderboardRequest
	(*GetLeaderboardReply)(nil),   // 13: contest.v1.GetLeaderboardReply
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),        // 15: common.v1.PageRequest
	(*v1.PageResponse)(nil),       // 16: common.v1.PageResponse
}
var file_api_contest_v1_contest_proto_depIdxs = []int32{
	0,  // 0: contest.v1.Contest.status:type_name -> contest.v1.ContestStatus
	14, // 1: contest.v1.Contest.start_at:type_name -> google.protobuf.Timestamp
	14, // 2: contest.v1.Contest.end_at:type_name -> google.protobuf.Timestamp
	14, // 3: contest.v1.Contest.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: contest.v1.Contest.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: contest.v1.Contest.problems:type_name -> contest.v1.ContestProblem
	0,  // 6: contest.v1.ContestSummary.status:type_name -> contest.v1.ContestStatus
	14, // 7: contest.v1.ContestSummary.start_at:type_name -> google.protobuf.Timestamp
	14, // 8: contest.v1.ContestSummary.end_at:type_name -> google.protobuf.Timestamp
	2,  // 9: contest.v1.GetContestReply.contest:type_name -> contest.v1.Contest
	14, // 10: contest.v1.ContestUpdate.start_at:type_name -> google.protobuf.Timestamp
	14, // 11: contest.v1.ContestUpdate.end_at:type_name -> google.protobuf.Timestamp
	1,  // 12: contest.v1.ContestUpdate.problems:type_name -> contest.v1.ContestProblem
	7,  // 13: contest.v1.UpdateContestRequest.contest:type_name -> contest.v1.ContestUpdate
	2,  // 14: contest.v1.UpdateContestReply.contest:type_name -> contest.v1.Contest
	15, // 15: contest.v1.ListContestsRequest.page:type_name -> common.v1.PageRequest
	0,  // 16: contest.v1.ListContestsRequest.status:type_name -> contest.v1.ContestStatus
	3,  // 17: contest.v1.ListContestsReply.items:type_name -> contest.v1.ContestSummary
	16, // 18: contest.v1.ListContestsReply.page:type_name -> common.v1.PageResponse
	15, // 19: contest.v1.GetLeaderboardRequest.page:type_name -> common.v1.PageRequest
	4,  // 20: contest.v1.GetLeaderboardReply.items:type_name -> contest.v1.LeaderboardEntry
	16, // 21: contest.v1.GetLeaderboardReply.page:type_name -> common.v1.PageResponse
	5,  // 22: contest.v1.ContestService.GetContest:input_type -> contest.v1.GetContestRequest
	10, // 23: contest.v1.ContestService.ListContests:input_type -> contest.v1.ListContestsRequest
	8,  // 24: contest.v1.ContestService.UpdateContest:input_type -> contest.v1.UpdateContestRequest
	12, // 25: contest.v1.ContestService.GetLeaderboard:input_type -> contest.v1.GetLeaderboardRequest
	6,  // 26: contest.v1.ContestService.GetContest:output_type -> contest.v1.GetContestReply
	11, // 27: contest.v1.ContestService.ListContests:output_type -> contest.v1.ListContestsReply
	9,  // 28: contest.v1.ContestService.UpdateContest:output_type -> contest.v1.UpdateContestReply
	13, // 29: contest.v1.ContestService.GetLeaderboard:output_type -> contest.v1.GetLeaderboardReply
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_contest_v1_contest_proto_init() }
func file_api_contest_v1_contest_proto_init() {
	if File_api_contest_v1_contest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_contest_v1_contest_proto_rawDesc), len(file_api_contest_v1_contest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_contest_v1_contest_proto_goTypes,
		DependencyIndexes: file_api_contest_v1_contest_proto_depIdxs,
		EnumInfos:         file_api_contest_v1_contest_proto_enumTypes,
		MessageInfos:      file_api_contest_v1_contest_proto_msgTypes,
	}.Build()
	File_api_contest_v1_contest_proto = out.File
	file_api_contest_v1_contest_proto_goTypes = nil
	file_api_contest_v1_contest_proto_depIdxs = nil
}
