// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: services/user/internal/conf/conf.proto

package conf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Bootstrap with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Bootstrap) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Bootstrap with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BootstrapMultiError, or nil
// if none found.
func (m *Bootstrap) ValidateAll() error {
	return m.validate(true)
}

func (m *Bootstrap) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetService()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Service",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Service",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetService()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Service",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetServer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Server",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Server",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetServer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Server",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAuth()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Auth",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Auth",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuth()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Auth",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRegistry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Registry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BootstrapMultiError(errors)
	}

	return nil
}

// BootstrapMultiError is an error wrapping multiple validation errors returned
// by Bootstrap.ValidateAll() if the designated constraints aren't met.
type BootstrapMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BootstrapMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BootstrapMultiError) AllErrors() []error { return m }

// BootstrapValidationError is the validation error returned by
// Bootstrap.Validate if the designated constraints aren't met.
type BootstrapValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BootstrapValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BootstrapValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BootstrapValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BootstrapValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BootstrapValidationError) ErrorName() string { return "BootstrapValidationError" }

// Error satisfies the builtin error interface
func (e BootstrapValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBootstrap.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BootstrapValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BootstrapValidationError{}

// Validate checks the field values on ServiceProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ServiceProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ServiceProtoMultiError, or
// nil if none found.
func (m *ServiceProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return ServiceProtoMultiError(errors)
	}

	return nil
}

// ServiceProtoMultiError is an error wrapping multiple validation errors
// returned by ServiceProto.ValidateAll() if the designated constraints aren't met.
type ServiceProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceProtoMultiError) AllErrors() []error { return m }

// ServiceProtoValidationError is the validation error returned by
// ServiceProto.Validate if the designated constraints aren't met.
type ServiceProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceProtoValidationError) ErrorName() string { return "ServiceProtoValidationError" }

// Error satisfies the builtin error interface
func (e ServiceProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceProtoValidationError{}

// Validate checks the field values on ServerProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ServerProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServerProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ServerProtoMultiError, or
// nil if none found.
func (m *ServerProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ServerProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGrpc()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServerProtoValidationError{
					field:  "Grpc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServerProtoValidationError{
					field:  "Grpc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGrpc()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServerProtoValidationError{
				field:  "Grpc",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ServerProtoMultiError(errors)
	}

	return nil
}

// ServerProtoMultiError is an error wrapping multiple validation errors
// returned by ServerProto.ValidateAll() if the designated constraints aren't met.
type ServerProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServerProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServerProtoMultiError) AllErrors() []error { return m }

// ServerProtoValidationError is the validation error returned by
// ServerProto.Validate if the designated constraints aren't met.
type ServerProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerProtoValidationError) ErrorName() string { return "ServerProtoValidationError" }

// Error satisfies the builtin error interface
func (e ServerProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServerProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerProtoValidationError{}

// Validate checks the field values on GRPCProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GRPCProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GRPCProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GRPCProtoMultiError, or nil
// if none found.
func (m *GRPCProto) ValidateAll() error {
	return m.validate(true)
}

func (m *GRPCProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	if len(errors) > 0 {
		return GRPCProtoMultiError(errors)
	}

	return nil
}

// GRPCProtoMultiError is an error wrapping multiple validation errors returned
// by GRPCProto.ValidateAll() if the designated constraints aren't met.
type GRPCProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GRPCProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GRPCProtoMultiError) AllErrors() []error { return m }

// GRPCProtoValidationError is the validation error returned by
// GRPCProto.Validate if the designated constraints aren't met.
type GRPCProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GRPCProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GRPCProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GRPCProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GRPCProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GRPCProtoValidationError) ErrorName() string { return "GRPCProtoValidationError" }

// Error satisfies the builtin error interface
func (e GRPCProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGRPCProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GRPCProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GRPCProtoValidationError{}

// Validate checks the field values on DataProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DataProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DataProtoMultiError, or nil
// if none found.
func (m *DataProto) ValidateAll() error {
	return m.validate(true)
}

func (m *DataProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MysqlDsn

	// no validation rules for RedisAddr

	// no validation rules for RedisPassword

	// no validation rules for RedisDb

	// no validation rules for RedisNamespace

	if len(errors) > 0 {
		return DataProtoMultiError(errors)
	}

	return nil
}

// DataProtoMultiError is an error wrapping multiple validation errors returned
// by DataProto.ValidateAll() if the designated constraints aren't met.
type DataProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataProtoMultiError) AllErrors() []error { return m }

// DataProtoValidationError is the validation error returned by
// DataProto.Validate if the designated constraints aren't met.
type DataProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataProtoValidationError) ErrorName() string { return "DataProtoValidationError" }

// Error satisfies the builtin error interface
func (e DataProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataProtoValidationError{}

// Validate checks the field values on AuthProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AuthProtoMultiError, or nil
// if none found.
func (m *AuthProto) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessTokenTtl

	// no validation rules for RefreshTokenTtl

	// no validation rules for AccessTokenKey

	// no validation rules for Issuer

	// no validation rules for Audience

	if all {
		switch v := interface{}(m.GetPassword()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthProtoValidationError{
					field:  "Password",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthProtoValidationError{
					field:  "Password",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPassword()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthProtoValidationError{
				field:  "Password",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuthProtoMultiError(errors)
	}

	return nil
}

// AuthProtoMultiError is an error wrapping multiple validation errors returned
// by AuthProto.ValidateAll() if the designated constraints aren't met.
type AuthProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthProtoMultiError) AllErrors() []error { return m }

// AuthProtoValidationError is the validation error returned by
// AuthProto.Validate if the designated constraints aren't met.
type AuthProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthProtoValidationError) ErrorName() string { return "AuthProtoValidationError" }

// Error satisfies the builtin error interface
func (e AuthProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthProtoValidationError{}

// Validate checks the field values on PasswordProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PasswordProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PasswordProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PasswordProtoMultiError, or
// nil if none found.
func (m *PasswordProto) ValidateAll() error {
	return m.validate(true)
}

func (m *PasswordProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BcryptCost

	if len(errors) > 0 {
		return PasswordProtoMultiError(errors)
	}

	return nil
}

// PasswordProtoMultiError is an error wrapping multiple validation errors
// returned by PasswordProto.ValidateAll() if the designated constraints
// aren't met.
type PasswordProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PasswordProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PasswordProtoMultiError) AllErrors() []error { return m }

// PasswordProtoValidationError is the validation error returned by
// PasswordProto.Validate if the designated constraints aren't met.
type PasswordProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PasswordProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PasswordProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PasswordProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PasswordProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PasswordProtoValidationError) ErrorName() string { return "PasswordProtoValidationError" }

// Error satisfies the builtin error interface
func (e PasswordProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPasswordProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PasswordProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PasswordProtoValidationError{}

// Validate checks the field values on RegistryProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegistryProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegistryProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegistryProtoMultiError, or
// nil if none found.
func (m *RegistryProto) ValidateAll() error {
	return m.validate(true)
}

func (m *RegistryProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConsul()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegistryProtoValidationError{
					field:  "Consul",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegistryProtoValidationError{
					field:  "Consul",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConsul()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegistryProtoValidationError{
				field:  "Consul",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegistryProtoMultiError(errors)
	}

	return nil
}

// RegistryProtoMultiError is an error wrapping multiple validation errors
// returned by RegistryProto.ValidateAll() if the designated constraints
// aren't met.
type RegistryProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegistryProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegistryProtoMultiError) AllErrors() []error { return m }

// RegistryProtoValidationError is the validation error returned by
// RegistryProto.Validate if the designated constraints aren't met.
type RegistryProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegistryProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegistryProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegistryProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegistryProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegistryProtoValidationError) ErrorName() string { return "RegistryProtoValidationError" }

// Error satisfies the builtin error interface
func (e RegistryProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegistryProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegistryProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegistryProtoValidationError{}

// Validate checks the field values on ConsulProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConsulProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConsulProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConsulProtoMultiError, or
// nil if none found.
func (m *ConsulProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ConsulProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enabled

	// no validation rules for Address

	// no validation rules for Scheme

	// no validation rules for Datacenter

	// no validation rules for Token

	// no validation rules for ServiceId

	if len(errors) > 0 {
		return ConsulProtoMultiError(errors)
	}

	return nil
}

// ConsulProtoMultiError is an error wrapping multiple validation errors
// returned by ConsulProto.ValidateAll() if the designated constraints aren't met.
type ConsulProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsulProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsulProtoMultiError) AllErrors() []error { return m }

// ConsulProtoValidationError is the validation error returned by
// ConsulProto.Validate if the designated constraints aren't met.
type ConsulProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsulProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsulProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsulProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsulProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsulProtoValidationError) ErrorName() string { return "ConsulProtoValidationError" }

// Error satisfies the builtin error interface
func (e ConsulProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsulProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsulProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsulProtoValidationError{}
