// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: services/user/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *ServiceProto          `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Server        *ServerProto           `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Data          *DataProto             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *AuthProto             `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	Registry      *RegistryProto         `protobuf:"bytes,5,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetService() *ServiceProto {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Bootstrap) GetServer() *ServerProto {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *DataProto {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *AuthProto {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *RegistryProto {
	if x != nil {
		return x.Registry
	}
	return nil
}

type ServiceProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceProto) Reset() {
	*x = ServiceProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceProto) ProtoMessage() {}

func (x *ServiceProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceProto.ProtoReflect.Descriptor instead.
func (*ServiceProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServerProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *GRPCProto             `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerProto) Reset() {
	*x = ServerProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerProto) ProtoMessage() {}

func (x *ServerProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerProto.ProtoReflect.Descriptor instead.
func (*ServerProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *ServerProto) GetGrpc() *GRPCProto {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type GRPCProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCProto) Reset() {
	*x = GRPCProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCProto) ProtoMessage() {}

func (x *GRPCProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCProto.ProtoReflect.Descriptor instead.
func (*GRPCProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *GRPCProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DataProto struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MysqlDsn       string                 `protobuf:"bytes,1,opt,name=mysql_dsn,json=mysqlDsn,proto3" json:"mysql_dsn,omitempty"`
	RedisAddr      string                 `protobuf:"bytes,2,opt,name=redis_addr,json=redisAddr,proto3" json:"redis_addr,omitempty"`
	RedisPassword  string                 `protobuf:"bytes,3,opt,name=redis_password,json=redisPassword,proto3" json:"redis_password,omitempty"`
	RedisDb        int32                  `protobuf:"varint,4,opt,name=redis_db,json=redisDb,proto3" json:"redis_db,omitempty"`
	RedisNamespace string                 `protobuf:"bytes,5,opt,name=redis_namespace,json=redisNamespace,proto3" json:"redis_namespace,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DataProto) Reset() {
	*x = DataProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataProto) ProtoMessage() {}

func (x *DataProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataProto.ProtoReflect.Descriptor instead.
func (*DataProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *DataProto) GetMysqlDsn() string {
	if x != nil {
		return x.MysqlDsn
	}
	return ""
}

func (x *DataProto) GetRedisAddr() string {
	if x != nil {
		return x.RedisAddr
	}
	return ""
}

func (x *DataProto) GetRedisPassword() string {
	if x != nil {
		return x.RedisPassword
	}
	return ""
}

func (x *DataProto) GetRedisDb() int32 {
	if x != nil {
		return x.RedisDb
	}
	return 0
}

func (x *DataProto) GetRedisNamespace() string {
	if x != nil {
		return x.RedisNamespace
	}
	return ""
}

type AuthProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessTokenTtl  string                 `protobuf:"bytes,1,opt,name=access_token_ttl,json=accessTokenTtl,proto3" json:"access_token_ttl,omitempty"`
	RefreshTokenTtl string                 `protobuf:"bytes,2,opt,name=refresh_token_ttl,json=refreshTokenTtl,proto3" json:"refresh_token_ttl,omitempty"`
	AccessTokenKey  string                 `protobuf:"bytes,3,opt,name=access_token_key,json=accessTokenKey,proto3" json:"access_token_key,omitempty"`
	Issuer          string                 `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience        string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	Password        *PasswordProto         `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthProto) Reset() {
	*x = AuthProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthProto) ProtoMessage() {}

func (x *AuthProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthProto.ProtoReflect.Descriptor instead.
func (*AuthProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *AuthProto) GetAccessTokenTtl() string {
	if x != nil {
		return x.AccessTokenTtl
	}
	return ""
}

func (x *AuthProto) GetRefreshTokenTtl() string {
	if x != nil {
		return x.RefreshTokenTtl
	}
	return ""
}

func (x *AuthProto) GetAccessTokenKey() string {
	if x != nil {
		return x.AccessTokenKey
	}
	return ""
}

func (x *AuthProto) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *AuthProto) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *AuthProto) GetPassword() *PasswordProto {
	if x != nil {
		return x.Password
	}
	return nil
}

type PasswordProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BcryptCost    int32                  `protobuf:"varint,1,opt,name=bcrypt_cost,json=bcryptCost,proto3" json:"bcrypt_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordProto) Reset() {
	*x = PasswordProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordProto) ProtoMessage() {}

func (x *PasswordProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordProto.ProtoReflect.Descriptor instead.
func (*PasswordProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *PasswordProto) GetBcryptCost() int32 {
	if x != nil {
		return x.BcryptCost
	}
	return 0
}

type RegistryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consul        *ConsulProto           `protobuf:"bytes,1,opt,name=consul,proto3" json:"consul,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryProto) Reset() {
	*x = RegistryProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryProto) ProtoMessage() {}

func (x *RegistryProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryProto.ProtoReflect.Descriptor instead.
func (*RegistryProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *RegistryProto) GetConsul() *ConsulProto {
	if x != nil {
		return x.Consul
	}
	return nil
}

type ConsulProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Scheme        string                 `protobuf:"bytes,3,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Datacenter    string                 `protobuf:"bytes,4,opt,name=datacenter,proto3" json:"datacenter,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ServiceId     string                 `protobuf:"bytes,6,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsulProto) Reset() {
	*x = ConsulProto{}
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsulProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsulProto) ProtoMessage() {}

func (x *ConsulProto) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsulProto.ProtoReflect.Descriptor instead.
func (*ConsulProto) Descriptor() ([]byte, []int) {
	return file_services_user_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *ConsulProto) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConsulProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConsulProto) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *ConsulProto) GetDatacenter() string {
	if x != nil {
		return x.Datacenter
	}
	return ""
}

func (x *ConsulProto) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConsulProto) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

var File_services_user_internal_conf_conf_proto protoreflect.FileDescriptor

const file_services_user_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	"&services/user/internal/conf/conf.proto\x12\tuser.conf\"\xf8\x01\n" +
	"\tBootstrap\x121\n" +
	"\aservice\x18\x01 \x01(\v2\x17.user.conf.ServiceProtoR\aservice\x12.\n" +
	"\x06server\x18\x02 \x01(\v2\x16.user.conf.ServerProtoR\x06server\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.user.conf.DataProtoR\x04data\x12(\n" +
	"\x04auth\x18\x04 \x01(\v2\x14.user.conf.AuthProtoR\x04auth\x124\n" +
	"\bregistry\x18\x05 \x01(\v2\x18.user.conf.RegistryProtoR\bregistry\"\"\n" +
	"\fServiceProto\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\vServerProto\x12(\n" +
	"\x04grpc\x18\x01 \x01(\v2\x14.user.conf.GRPCProtoR\x04grpc\"%\n" +
	"\tGRPCProto\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\xb2\x01\n" +
	"\tDataProto\x12\x1b\n" +
	"\tmysql_dsn\x18\x01 \x01(\tR\bmysqlDsn\x12\x1d\n" +
	"\n" +
	"redis_addr\x18\x02 \x01(\tR\tredisAddr\x12%\n" +
	"\x0eredis_password\x18\x03 \x01(\tR\rredisPassword\x12\x19\n" +
	"\bredis_db\x18\x04 \x01(\x05R\aredisDb\x12'\n" +
	"\x0fredis_namespace\x18\x05 \x01(\tR\x0eredisNamespace\"\xf5\x01\n" +
	"\tAuthProto\x12(\n" +
	"\x10access_token_ttl\x18\x01 \x01(\tR\x0eaccessTokenTtl\x12*\n" +
	"\x11refresh_token_ttl\x18\x02 \x01(\tR\x0frefreshTokenTtl\x12(\n" +
	"\x10access_token_key\x18\x03 \x01(\tR\x0eaccessTokenKey\x12\x16\n" +
	"\x06issuer\x18\x04 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x124\n" +
	"\bpassword\x18\x06 \x01(\v2\x18.user.conf.PasswordProtoR\bpassword\"0\n" +
	"\rPasswordProto\x12\x1f\n" +
	"\vbcrypt_cost\x18\x01 \x01(\x05R\n" +
	"bcryptCost\"?\n" +
	"\rRegistryProto\x12.\n" +
	"\x06consul\x18\x01 \x01(\v2\x16.user.conf.ConsulProtoR\x06consul\"\xae\x01\n" +
	"\vConsulProto\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x16\n" +
	"\x06scheme\x18\x03 \x01(\tR\x06scheme\x12\x1e\n" +
	"\n" +
	"datacenter\x18\x04 \x01(\tR\n" +
	"datacenter\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"service_id\x18\x06 \x01(\tR\tserviceIdBBZ@github.com/viggggil/go_oj_agent/services/user/internal/conf;confb\x06proto3"

var (
	file_services_user_internal_conf_conf_proto_rawDescOnce sync.Once
	file_services_user_internal_conf_conf_proto_rawDescData []byte
)

func file_services_user_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_services_user_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_services_user_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_user_internal_conf_conf_proto_rawDesc), len(file_services_user_internal_conf_conf_proto_rawDesc)))
	})
	return file_services_user_internal_conf_conf_proto_rawDescData
}

var file_services_user_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_services_user_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),     // 0: user.conf.Bootstrap
	(*ServiceProto)(nil),  // 1: user.conf.ServiceProto
	(*ServerProto)(nil),   // 2: user.conf.ServerProto
	(*GRPCProto)(nil),     // 3: user.conf.GRPCProto
	(*DataProto)(nil),     // 4: user.conf.DataProto
	(*AuthProto)(nil),     // 5: user.conf.AuthProto
	(*PasswordProto)(nil), // 6: user.conf.PasswordProto
	(*RegistryProto)(nil), // 7: user.conf.RegistryProto
	(*ConsulProto)(nil),   // 8: user.conf.ConsulProto
}
var file_services_user_internal_conf_conf_proto_depIdxs = []int32{
	1, // 0: user.conf.Bootstrap.service:type_name -> user.conf.ServiceProto
	2, // 1: user.conf.Bootstrap.server:type_name -> user.conf.ServerProto
	4, // 2: user.conf.Bootstrap.data:type_name -> user.conf.DataProto
	5, // 3: user.conf.Bootstrap.auth:type_name -> user.conf.AuthProto
	7, // 4: user.conf.Bootstrap.registry:type_name -> user.conf.RegistryProto
	3, // 5: user.conf.ServerProto.grpc:type_name -> user.conf.GRPCProto
	6, // 6: user.conf.AuthProto.password:type_name -> user.conf.PasswordProto
	8, // 7: user.conf.RegistryProto.consul:type_name -> user.conf.ConsulProto
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_services_user_internal_conf_conf_proto_init() }
func file_services_user_internal_conf_conf_proto_init() {
	if File_services_user_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_user_internal_conf_conf_proto_rawDesc), len(file_services_user_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_user_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_services_user_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_services_user_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_services_user_internal_conf_conf_proto = out.File
	file_services_user_internal_conf_conf_proto_goTypes = nil
	file_services_user_internal_conf_conf_proto_depIdxs = nil
}
