// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: services/contest/internal/conf/conf.proto

package conf

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Bootstrap with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Bootstrap) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Bootstrap with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BootstrapMultiError, or nil
// if none found.
func (m *Bootstrap) ValidateAll() error {
	return m.validate(true)
}

func (m *Bootstrap) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetService()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Service",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Service",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetService()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Service",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetServer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Server",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Server",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetServer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Server",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRegistry()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Registry",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRegistry()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Registry",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetInternalAuth()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "InternalAuth",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "InternalAuth",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInternalAuth()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "InternalAuth",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetJudge()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Judge",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Judge",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetJudge()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Judge",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetMessaging()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Messaging",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Messaging",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMessaging()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Messaging",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetProblem()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Problem",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BootstrapValidationError{
					field:  "Problem",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetProblem()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BootstrapValidationError{
				field:  "Problem",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BootstrapMultiError(errors)
	}

	return nil
}

// BootstrapMultiError is an error wrapping multiple validation errors returned
// by Bootstrap.ValidateAll() if the designated constraints aren't met.
type BootstrapMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BootstrapMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BootstrapMultiError) AllErrors() []error { return m }

// BootstrapValidationError is the validation error returned by
// Bootstrap.Validate if the designated constraints aren't met.
type BootstrapValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BootstrapValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BootstrapValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BootstrapValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BootstrapValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BootstrapValidationError) ErrorName() string { return "BootstrapValidationError" }

// Error satisfies the builtin error interface
func (e BootstrapValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBootstrap.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BootstrapValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BootstrapValidationError{}

// Validate checks the field values on MessagingProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *MessagingProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on MessagingProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in MessagingProtoMultiError,
// or nil if none found.
func (m *MessagingProto) ValidateAll() error {
	return m.validate(true)
}

func (m *MessagingProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Exchange

	// no validation rules for Queue

	// no validation rules for DeadLetterQueue

	// no validation rules for Prefetch

	if len(errors) > 0 {
		return MessagingProtoMultiError(errors)
	}

	return nil
}

// MessagingProtoMultiError is an error wrapping multiple validation errors
// returned by MessagingProto.ValidateAll() if the designated constraints
// aren't met.
type MessagingProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m MessagingProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m MessagingProtoMultiError) AllErrors() []error { return m }

// MessagingProtoValidationError is the validation error returned by
// MessagingProto.Validate if the designated constraints aren't met.
type MessagingProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessagingProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessagingProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessagingProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessagingProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessagingProtoValidationError) ErrorName() string { return "MessagingProtoValidationError" }

// Error satisfies the builtin error interface
func (e MessagingProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessagingProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessagingProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessagingProtoValidationError{}

// Validate checks the field values on ServiceProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ServiceProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServiceProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ServiceProtoMultiError, or
// nil if none found.
func (m *ServiceProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ServiceProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return ServiceProtoMultiError(errors)
	}

	return nil
}

// ServiceProtoMultiError is an error wrapping multiple validation errors
// returned by ServiceProto.ValidateAll() if the designated constraints aren't met.
type ServiceProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServiceProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServiceProtoMultiError) AllErrors() []error { return m }

// ServiceProtoValidationError is the validation error returned by
// ServiceProto.Validate if the designated constraints aren't met.
type ServiceProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServiceProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServiceProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServiceProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServiceProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServiceProtoValidationError) ErrorName() string { return "ServiceProtoValidationError" }

// Error satisfies the builtin error interface
func (e ServiceProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServiceProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServiceProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServiceProtoValidationError{}

// Validate checks the field values on ServerProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ServerProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ServerProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ServerProtoMultiError, or
// nil if none found.
func (m *ServerProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ServerProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetGrpc()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ServerProtoValidationError{
					field:  "Grpc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ServerProtoValidationError{
					field:  "Grpc",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetGrpc()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ServerProtoValidationError{
				field:  "Grpc",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ServerProtoMultiError(errors)
	}

	return nil
}

// ServerProtoMultiError is an error wrapping multiple validation errors
// returned by ServerProto.ValidateAll() if the designated constraints aren't met.
type ServerProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ServerProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ServerProtoMultiError) AllErrors() []error { return m }

// ServerProtoValidationError is the validation error returned by
// ServerProto.Validate if the designated constraints aren't met.
type ServerProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ServerProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ServerProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ServerProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ServerProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ServerProtoValidationError) ErrorName() string { return "ServerProtoValidationError" }

// Error satisfies the builtin error interface
func (e ServerProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sServerProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ServerProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ServerProtoValidationError{}

// Validate checks the field values on GRPCProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GRPCProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GRPCProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GRPCProtoMultiError, or nil
// if none found.
func (m *GRPCProto) ValidateAll() error {
	return m.validate(true)
}

func (m *GRPCProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	// no validation rules for MaxReceiveMessageBytes

	if len(errors) > 0 {
		return GRPCProtoMultiError(errors)
	}

	return nil
}

// GRPCProtoMultiError is an error wrapping multiple validation errors returned
// by GRPCProto.ValidateAll() if the designated constraints aren't met.
type GRPCProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GRPCProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GRPCProtoMultiError) AllErrors() []error { return m }

// GRPCProtoValidationError is the validation error returned by
// GRPCProto.Validate if the designated constraints aren't met.
type GRPCProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GRPCProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GRPCProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GRPCProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GRPCProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GRPCProtoValidationError) ErrorName() string { return "GRPCProtoValidationError" }

// Error satisfies the builtin error interface
func (e GRPCProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGRPCProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GRPCProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GRPCProtoValidationError{}

// Validate checks the field values on DataProto with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DataProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DataProtoMultiError, or nil
// if none found.
func (m *DataProto) ValidateAll() error {
	return m.validate(true)
}

func (m *DataProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MysqlDsn

	if len(errors) > 0 {
		return DataProtoMultiError(errors)
	}

	return nil
}

// DataProtoMultiError is an error wrapping multiple validation errors returned
// by DataProto.ValidateAll() if the designated constraints aren't met.
type DataProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataProtoMultiError) AllErrors() []error { return m }

// DataProtoValidationError is the validation error returned by
// DataProto.Validate if the designated constraints aren't met.
type DataProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataProtoValidationError) ErrorName() string { return "DataProtoValidationError" }

// Error satisfies the builtin error interface
func (e DataProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataProtoValidationError{}

// Validate checks the field values on RegistryProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RegistryProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegistryProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RegistryProtoMultiError, or
// nil if none found.
func (m *RegistryProto) ValidateAll() error {
	return m.validate(true)
}

func (m *RegistryProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConsul()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegistryProtoValidationError{
					field:  "Consul",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegistryProtoValidationError{
					field:  "Consul",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConsul()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegistryProtoValidationError{
				field:  "Consul",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RegistryProtoMultiError(errors)
	}

	return nil
}

// RegistryProtoMultiError is an error wrapping multiple validation errors
// returned by RegistryProto.ValidateAll() if the designated constraints
// aren't met.
type RegistryProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegistryProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegistryProtoMultiError) AllErrors() []error { return m }

// RegistryProtoValidationError is the validation error returned by
// RegistryProto.Validate if the designated constraints aren't met.
type RegistryProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegistryProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegistryProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegistryProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegistryProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegistryProtoValidationError) ErrorName() string { return "RegistryProtoValidationError" }

// Error satisfies the builtin error interface
func (e RegistryProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegistryProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegistryProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegistryProtoValidationError{}

// Validate checks the field values on ConsulProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ConsulProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConsulProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConsulProtoMultiError, or
// nil if none found.
func (m *ConsulProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ConsulProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Enabled

	// no validation rules for Address

	// no validation rules for Scheme

	// no validation rules for Datacenter

	// no validation rules for Token

	// no validation rules for ServiceId

	if len(errors) > 0 {
		return ConsulProtoMultiError(errors)
	}

	return nil
}

// ConsulProtoMultiError is an error wrapping multiple validation errors
// returned by ConsulProto.ValidateAll() if the designated constraints aren't met.
type ConsulProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConsulProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConsulProtoMultiError) AllErrors() []error { return m }

// ConsulProtoValidationError is the validation error returned by
// ConsulProto.Validate if the designated constraints aren't met.
type ConsulProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConsulProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConsulProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConsulProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConsulProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConsulProtoValidationError) ErrorName() string { return "ConsulProtoValidationError" }

// Error satisfies the builtin error interface
func (e ConsulProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConsulProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConsulProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConsulProtoValidationError{}

// Validate checks the field values on InternalAuthProto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *InternalAuthProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InternalAuthProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InternalAuthProtoMultiError, or nil if none found.
func (m *InternalAuthProto) ValidateAll() error {
	return m.validate(true)
}

func (m *InternalAuthProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PublicKeyFile

	// no validation rules for KeyId

	// no validation rules for Issuer

	// no validation rules for Audience

	// no validation rules for Subject

	// no validation rules for MaxTokenTtl

	// no validation rules for ClockSkew

	for idx, item := range m.GetAdditionalCallers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, InternalAuthProtoValidationError{
						field:  fmt.Sprintf("AdditionalCallers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, InternalAuthProtoValidationError{
						field:  fmt.Sprintf("AdditionalCallers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InternalAuthProtoValidationError{
					field:  fmt.Sprintf("AdditionalCallers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return InternalAuthProtoMultiError(errors)
	}

	return nil
}

// InternalAuthProtoMultiError is an error wrapping multiple validation errors
// returned by InternalAuthProto.ValidateAll() if the designated constraints
// aren't met.
type InternalAuthProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InternalAuthProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InternalAuthProtoMultiError) AllErrors() []error { return m }

// InternalAuthProtoValidationError is the validation error returned by
// InternalAuthProto.Validate if the designated constraints aren't met.
type InternalAuthProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InternalAuthProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InternalAuthProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InternalAuthProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InternalAuthProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InternalAuthProtoValidationError) ErrorName() string {
	return "InternalAuthProtoValidationError"
}

// Error satisfies the builtin error interface
func (e InternalAuthProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInternalAuthProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InternalAuthProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InternalAuthProtoValidationError{}

// Validate checks the field values on InternalCallerProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InternalCallerProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InternalCallerProto with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InternalCallerProtoMultiError, or nil if none found.
func (m *InternalCallerProto) ValidateAll() error {
	return m.validate(true)
}

func (m *InternalCallerProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PublicKeyFile

	// no validation rules for KeyId

	// no validation rules for Issuer

	// no validation rules for Subject

	if len(errors) > 0 {
		return InternalCallerProtoMultiError(errors)
	}

	return nil
}

// InternalCallerProtoMultiError is an error wrapping multiple validation
// errors returned by InternalCallerProto.ValidateAll() if the designated
// constraints aren't met.
type InternalCallerProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InternalCallerProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InternalCallerProtoMultiError) AllErrors() []error { return m }

// InternalCallerProtoValidationError is the validation error returned by
// InternalCallerProto.Validate if the designated constraints aren't met.
type InternalCallerProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InternalCallerProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InternalCallerProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InternalCallerProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InternalCallerProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InternalCallerProtoValidationError) ErrorName() string {
	return "InternalCallerProtoValidationError"
}

// Error satisfies the builtin error interface
func (e InternalCallerProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInternalCallerProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InternalCallerProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InternalCallerProtoValidationError{}

// Validate checks the field values on ClientProto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClientProto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClientProto with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ClientProtoMultiError, or
// nil if none found.
func (m *ClientProto) ValidateAll() error {
	return m.validate(true)
}

func (m *ClientProto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Endpoint

	// no validation rules for Timeout

	// no validation rules for PrivateKeyFile

	// no validation rules for KeyId

	// no validation rules for Issuer

	// no validation rules for Audience

	// no validation rules for Subject

	// no validation rules for TokenTtl

	if len(errors) > 0 {
		return ClientProtoMultiError(errors)
	}

	return nil
}

// ClientProtoMultiError is an error wrapping multiple validation errors
// returned by ClientProto.ValidateAll() if the designated constraints aren't met.
type ClientProtoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClientProtoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClientProtoMultiError) AllErrors() []error { return m }

// ClientProtoValidationError is the validation error returned by
// ClientProto.Validate if the designated constraints aren't met.
type ClientProtoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClientProtoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClientProtoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClientProtoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClientProtoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClientProtoValidationError) ErrorName() string { return "ClientProtoValidationError" }

// Error satisfies the builtin error interface
func (e ClientProtoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClientProto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClientProtoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClientProtoValidationError{}
