service:
  name: gateway-service
server:
  http:
    address: "${SERVER_HTTP_ADDRESS}"
    timeout: "30s"
auth:
  access_token_key: "${AUTH_ACCESS_TOKEN_KEY}"
  access_token_public_key_file: "${AUTH_ACCESS_TOKEN_PUBLIC_KEY_FILE}"
  access_token_key_id: "${AUTH_ACCESS_TOKEN_KEY_ID}"
  issuer: "${AUTH_ISSUER}"
  audience: "${AUTH_AUDIENCE}"
  internal_private_key_file: "${AUTH_INTERNAL_PRIVATE_KEY_FILE}"
  internal_key_id: "${AUTH_INTERNAL_KEY_ID}"
  internal_issuer: "${AUTH_INTERNAL_ISSUER}"
  internal_audience: "${AUTH_INTERNAL_AUDIENCE}"
  internal_token_ttl: "${AUTH_INTERNAL_TOKEN_TTL}"
clients:
  user:
    name: user-service
    endpoint: "${CLIENTS_USER_ENDPOINT}"
    timeout: "3s"
  problem:
    name: problem-service
    endpoint: "${CLIENTS_PROBLEM_ENDPOINT}"
    timeout: "30s"
  submission:
    name: submission-service
    endpoint: ""
    timeout: "3s"
registry:
  consul:
    enabled: false
