service:
  name: gateway-service
server:
  http:
    address: ":8080"
    timeout: "30s"
auth:
  access_token_key: "replace-with-the-same-secret-as-user-service"
  access_token_public_key_file: ""
  access_token_key_id: "user-access-2026-09"
  issuer: "go-oj-agent"
  audience: "go-oj-gateway"
  internal_private_key_file: ""
  internal_key_id: "gateway-internal-2026-09"
  internal_issuer: "go-oj-gateway"
  internal_audience: "problem-service"
  internal_token_ttl: "30s"
clients:
  user:
    name: "user-service"
    endpoint: "127.0.0.1:9001"
    timeout: "3s"
  problem:
    name: "problem-service"
    endpoint: "127.0.0.1:9002"
    timeout: "30s"
  submission:
    name: "submission-service"
    endpoint: ""
    timeout: "3s"
registry:
  consul:
    enabled: false
    address: "127.0.0.1:8500"
    scheme: "http"
