// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package problemv1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v3/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsProblemErrorReasonInvalidArgument(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_INVALID_ARGUMENT.String() && e.Code == 400
}

func ErrorProblemErrorReasonInvalidArgument(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ProblemErrorReason_PROBLEM_ERROR_REASON_INVALID_ARGUMENT.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_NOT_FOUND.String() && e.Code == 404
}

func ErrorProblemErrorReasonNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ProblemErrorReason_PROBLEM_ERROR_REASON_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorProblemErrorReasonAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ProblemErrorReason_PROBLEM_ERROR_REASON_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonPermissionDenied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_PERMISSION_DENIED.String() && e.Code == 403
}

func ErrorProblemErrorReasonPermissionDenied(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ProblemErrorReason_PROBLEM_ERROR_REASON_PERMISSION_DENIED.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonInvalidStatus(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_INVALID_STATUS.String() && e.Code == 412
}

func ErrorProblemErrorReasonInvalidStatus(format string, args ...interface{}) *errors.Error {
	return errors.New(412, ProblemErrorReason_PROBLEM_ERROR_REASON_INVALID_STATUS.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonTestcaseNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_TESTCASE_NOT_FOUND.String() && e.Code == 404
}

func ErrorProblemErrorReasonTestcaseNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ProblemErrorReason_PROBLEM_ERROR_REASON_TESTCASE_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonTestcaseAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_TESTCASE_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorProblemErrorReasonTestcaseAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ProblemErrorReason_PROBLEM_ERROR_REASON_TESTCASE_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}

func IsProblemErrorReasonStorageUnavailable(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ProblemErrorReason_PROBLEM_ERROR_REASON_STORAGE_UNAVAILABLE.String() && e.Code == 503
}

func ErrorProblemErrorReasonStorageUnavailable(format string, args ...interface{}) *errors.Error {
	return errors.New(503, ProblemErrorReason_PROBLEM_ERROR_REASON_STORAGE_UNAVAILABLE.String(), fmt.Sprintf(format, args...))
}
