# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpcgen.api.submission.v1 import submission_pb2 as api_dot_submission_dot_v1_dot_submission__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/submission/v1/submission_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SubmissionServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSubmission = channel.unary_unary(
                '/submission.v1.SubmissionService/CreateSubmission',
                request_serializer=api_dot_submission_dot_v1_dot_submission__pb2.CreateSubmissionRequest.SerializeToString,
                response_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.CreateSubmissionResponse.FromString,
                _registered_method=True)
        self.GetSubmission = channel.unary_unary(
                '/submission.v1.SubmissionService/GetSubmission',
                request_serializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionRequest.SerializeToString,
                response_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionResponse.FromString,
                _registered_method=True)
        self.GetSubmissionSource = channel.unary_unary(
                '/submission.v1.SubmissionService/GetSubmissionSource',
                request_serializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionSourceRequest.SerializeToString,
                response_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionSourceResponse.FromString,
                _registered_method=True)
        self.ListSubmissions = channel.unary_unary(
                '/submission.v1.SubmissionService/ListSubmissions',
                request_serializer=api_dot_submission_dot_v1_dot_submission__pb2.ListSubmissionsRequest.SerializeToString,
                response_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.ListSubmissionsResponse.FromString,
                _registered_method=True)
        self.GetJudgeResult = channel.unary_unary(
                '/submission.v1.SubmissionService/GetJudgeResult',
                request_serializer=api_dot_submission_dot_v1_dot_submission__pb2.GetJudgeResultRequest.SerializeToString,
                response_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.GetJudgeResultResponse.FromString,
                _registered_method=True)
        self.RejudgeSubmission = channel.unary_unary(
                '/submission.v1.SubmissionService/RejudgeSubmission',
                request_serializer=api_dot_submission_dot_v1_dot_submission__pb2.RejudgeSubmissionRequest.SerializeToString,
                response_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.RejudgeSubmissionResponse.FromString,
                _registered_method=True)


class SubmissionServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubmissionSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSubmissions(self, request, context):
        """ListSubmissions also covers recent submissions through stable descending
        pagination; a separate ListRecentSubmissions RPC is intentionally omitted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJudgeResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejudgeSubmission(self, request, context):
        """RejudgeSubmission invalidates the old result and creates a new submission
        for the same user with the problem's current judge revision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SubmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSubmission,
                    request_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.CreateSubmissionRequest.FromString,
                    response_serializer=api_dot_submission_dot_v1_dot_submission__pb2.CreateSubmissionResponse.SerializeToString,
            ),
            'GetSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubmission,
                    request_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionRequest.FromString,
                    response_serializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionResponse.SerializeToString,
            ),
            'GetSubmissionSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubmissionSource,
                    request_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionSourceRequest.FromString,
                    response_serializer=api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionSourceResponse.SerializeToString,
            ),
            'ListSubmissions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSubmissions,
                    request_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.ListSubmissionsRequest.FromString,
                    response_serializer=api_dot_submission_dot_v1_dot_submission__pb2.ListSubmissionsResponse.SerializeToString,
            ),
            'GetJudgeResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJudgeResult,
                    request_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.GetJudgeResultRequest.FromString,
                    response_serializer=api_dot_submission_dot_v1_dot_submission__pb2.GetJudgeResultResponse.SerializeToString,
            ),
            'RejudgeSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.RejudgeSubmission,
                    request_deserializer=api_dot_submission_dot_v1_dot_submission__pb2.RejudgeSubmissionRequest.FromString,
                    response_serializer=api_dot_submission_dot_v1_dot_submission__pb2.RejudgeSubmissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'submission.v1.SubmissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('submission.v1.SubmissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SubmissionService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/submission.v1.SubmissionService/CreateSubmission',
            api_dot_submission_dot_v1_dot_submission__pb2.CreateSubmissionRequest.SerializeToString,
            api_dot_submission_dot_v1_dot_submission__pb2.CreateSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/submission.v1.SubmissionService/GetSubmission',
            api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionRequest.SerializeToString,
            api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubmissionSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/submission.v1.SubmissionService/GetSubmissionSource',
            api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionSourceRequest.SerializeToString,
            api_dot_submission_dot_v1_dot_submission__pb2.GetSubmissionSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSubmissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/submission.v1.SubmissionService/ListSubmissions',
            api_dot_submission_dot_v1_dot_submission__pb2.ListSubmissionsRequest.SerializeToString,
            api_dot_submission_dot_v1_dot_submission__pb2.ListSubmissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJudgeResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/submission.v1.SubmissionService/GetJudgeResult',
            api_dot_submission_dot_v1_dot_submission__pb2.GetJudgeResultRequest.SerializeToString,
            api_dot_submission_dot_v1_dot_submission__pb2.GetJudgeResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejudgeSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/submission.v1.SubmissionService/RejudgeSubmission',
            api_dot_submission_dot_v1_dot_submission__pb2.RejudgeSubmissionRequest.SerializeToString,
            api_dot_submission_dot_v1_dot_submission__pb2.RejudgeSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
