// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/submission/v1/submission.proto

package submissionv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Submission with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Submission) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Submission with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SubmissionMultiError, or
// nil if none found.
func (m *Submission) ValidateAll() error {
	return m.validate(true)
}

func (m *Submission) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for ProblemId

	// no validation rules for Language

	// no validation rules for SourceCode

	// no validation rules for Status

	// no validation rules for Verdict

	// no validation rules for TimeMs

	// no validation rules for MemoryKb

	// no validation rules for TestcaseVersion

	if len(errors) > 0 {
		return SubmissionMultiError(errors)
	}

	return nil
}

// SubmissionMultiError is an error wrapping multiple validation errors
// returned by Submission.ValidateAll() if the designated constraints aren't met.
type SubmissionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmissionMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmissionMultiError) AllErrors() []error { return m }

// SubmissionValidationError is the validation error returned by
// Submission.Validate if the designated constraints aren't met.
type SubmissionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmissionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmissionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmissionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmissionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmissionValidationError) ErrorName() string { return "SubmissionValidationError" }

// Error satisfies the builtin error interface
func (e SubmissionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmission.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmissionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmissionValidationError{}

// Validate checks the field values on SubmissionCaseResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SubmissionCaseResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SubmissionCaseResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SubmissionCaseResultMultiError, or nil if none found.
func (m *SubmissionCaseResult) ValidateAll() error {
	return m.validate(true)
}

func (m *SubmissionCaseResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SubmissionId

	// no validation rules for CaseNo

	// no validation rules for Verdict

	// no validation rules for TimeMs

	// no validation rules for MemoryKb

	// no validation rules for Message

	if len(errors) > 0 {
		return SubmissionCaseResultMultiError(errors)
	}

	return nil
}

// SubmissionCaseResultMultiError is an error wrapping multiple validation
// errors returned by SubmissionCaseResult.ValidateAll() if the designated
// constraints aren't met.
type SubmissionCaseResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SubmissionCaseResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SubmissionCaseResultMultiError) AllErrors() []error { return m }

// SubmissionCaseResultValidationError is the validation error returned by
// SubmissionCaseResult.Validate if the designated constraints aren't met.
type SubmissionCaseResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SubmissionCaseResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SubmissionCaseResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SubmissionCaseResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SubmissionCaseResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SubmissionCaseResultValidationError) ErrorName() string {
	return "SubmissionCaseResultValidationError"
}

// Error satisfies the builtin error interface
func (e SubmissionCaseResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSubmissionCaseResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SubmissionCaseResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SubmissionCaseResultValidationError{}

// Validate checks the field values on JudgeResult with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JudgeResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JudgeResult with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JudgeResultMultiError, or
// nil if none found.
func (m *JudgeResult) ValidateAll() error {
	return m.validate(true)
}

func (m *JudgeResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	// no validation rules for Status

	// no validation rules for Verdict

	// no validation rules for TimeMs

	// no validation rules for MemoryKb

	for idx, item := range m.GetCaseResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, JudgeResultValidationError{
						field:  fmt.Sprintf("CaseResults[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, JudgeResultValidationError{
						field:  fmt.Sprintf("CaseResults[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return JudgeResultValidationError{
					field:  fmt.Sprintf("CaseResults[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return JudgeResultMultiError(errors)
	}

	return nil
}

// JudgeResultMultiError is an error wrapping multiple validation errors
// returned by JudgeResult.ValidateAll() if the designated constraints aren't met.
type JudgeResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JudgeResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JudgeResultMultiError) AllErrors() []error { return m }

// JudgeResultValidationError is the validation error returned by
// JudgeResult.Validate if the designated constraints aren't met.
type JudgeResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JudgeResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JudgeResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JudgeResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JudgeResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JudgeResultValidationError) ErrorName() string { return "JudgeResultValidationError" }

// Error satisfies the builtin error interface
func (e JudgeResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJudgeResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JudgeResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JudgeResultValidationError{}

// Validate checks the field values on CreateSubmissionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSubmissionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSubmissionRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSubmissionRequestMultiError, or nil if none found.
func (m *CreateSubmissionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSubmissionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateSubmissionRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateSubmissionRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateSubmissionRequestValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ProblemId

	// no validation rules for Language

	// no validation rules for SourceCode

	if len(errors) > 0 {
		return CreateSubmissionRequestMultiError(errors)
	}

	return nil
}

// CreateSubmissionRequestMultiError is an error wrapping multiple validation
// errors returned by CreateSubmissionRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateSubmissionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSubmissionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSubmissionRequestMultiError) AllErrors() []error { return m }

// CreateSubmissionRequestValidationError is the validation error returned by
// CreateSubmissionRequest.Validate if the designated constraints aren't met.
type CreateSubmissionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSubmissionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSubmissionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSubmissionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSubmissionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSubmissionRequestValidationError) ErrorName() string {
	return "CreateSubmissionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSubmissionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSubmissionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSubmissionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSubmissionRequestValidationError{}

// Validate checks the field values on CreateSubmissionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateSubmissionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateSubmissionResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateSubmissionResponseMultiError, or nil if none found.
func (m *CreateSubmissionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateSubmissionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for SubmissionId

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateSubmissionResponseMultiError(errors)
	}

	return nil
}

// CreateSubmissionResponseMultiError is an error wrapping multiple validation
// errors returned by CreateSubmissionResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateSubmissionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateSubmissionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateSubmissionResponseMultiError) AllErrors() []error { return m }

// CreateSubmissionResponseValidationError is the validation error returned by
// CreateSubmissionResponse.Validate if the designated constraints aren't met.
type CreateSubmissionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateSubmissionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateSubmissionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateSubmissionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateSubmissionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateSubmissionResponseValidationError) ErrorName() string {
	return "CreateSubmissionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateSubmissionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateSubmissionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateSubmissionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateSubmissionResponseValidationError{}

// Validate checks the field values on GetSubmissionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubmissionRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubmissionRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubmissionRequestMultiError, or nil if none found.
func (m *GetSubmissionRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubmissionRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSubmissionRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSubmissionRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSubmissionRequestValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SubmissionId

	if len(errors) > 0 {
		return GetSubmissionRequestMultiError(errors)
	}

	return nil
}

// GetSubmissionRequestMultiError is an error wrapping multiple validation
// errors returned by GetSubmissionRequest.ValidateAll() if the designated
// constraints aren't met.
type GetSubmissionRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubmissionRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubmissionRequestMultiError) AllErrors() []error { return m }

// GetSubmissionRequestValidationError is the validation error returned by
// GetSubmissionRequest.Validate if the designated constraints aren't met.
type GetSubmissionRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubmissionRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubmissionRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubmissionRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubmissionRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubmissionRequestValidationError) ErrorName() string {
	return "GetSubmissionRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubmissionRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubmissionRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubmissionRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubmissionRequestValidationError{}

// Validate checks the field values on GetSubmissionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetSubmissionResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSubmissionResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSubmissionResponseMultiError, or nil if none found.
func (m *GetSubmissionResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSubmissionResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSubmission()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetSubmissionResponseValidationError{
					field:  "Submission",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetSubmissionResponseValidationError{
					field:  "Submission",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubmission()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetSubmissionResponseValidationError{
				field:  "Submission",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetSubmissionResponseMultiError(errors)
	}

	return nil
}

// GetSubmissionResponseMultiError is an error wrapping multiple validation
// errors returned by GetSubmissionResponse.ValidateAll() if the designated
// constraints aren't met.
type GetSubmissionResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSubmissionResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSubmissionResponseMultiError) AllErrors() []error { return m }

// GetSubmissionResponseValidationError is the validation error returned by
// GetSubmissionResponse.Validate if the designated constraints aren't met.
type GetSubmissionResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSubmissionResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSubmissionResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSubmissionResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSubmissionResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSubmissionResponseValidationError) ErrorName() string {
	return "GetSubmissionResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSubmissionResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSubmissionResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSubmissionResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSubmissionResponseValidationError{}

// Validate checks the field values on ListSubmissionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSubmissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSubmissionsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSubmissionsRequestMultiError, or nil if none found.
func (m *ListSubmissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSubmissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListSubmissionsRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListSubmissionsRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListSubmissionsRequestValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListSubmissionsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListSubmissionsRequestValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListSubmissionsRequestValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ProblemId

	// no validation rules for Status

	// no validation rules for Language

	if len(errors) > 0 {
		return ListSubmissionsRequestMultiError(errors)
	}

	return nil
}

// ListSubmissionsRequestMultiError is an error wrapping multiple validation
// errors returned by ListSubmissionsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListSubmissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSubmissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSubmissionsRequestMultiError) AllErrors() []error { return m }

// ListSubmissionsRequestValidationError is the validation error returned by
// ListSubmissionsRequest.Validate if the designated constraints aren't met.
type ListSubmissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSubmissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSubmissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSubmissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSubmissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSubmissionsRequestValidationError) ErrorName() string {
	return "ListSubmissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListSubmissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSubmissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSubmissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSubmissionsRequestValidationError{}

// Validate checks the field values on ListSubmissionsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListSubmissionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSubmissionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListSubmissionsResponseMultiError, or nil if none found.
func (m *ListSubmissionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSubmissionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListSubmissionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListSubmissionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListSubmissionsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListSubmissionsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListSubmissionsResponseValidationError{
					field:  "Page",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListSubmissionsResponseValidationError{
				field:  "Page",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListSubmissionsResponseMultiError(errors)
	}

	return nil
}

// ListSubmissionsResponseMultiError is an error wrapping multiple validation
// errors returned by ListSubmissionsResponse.ValidateAll() if the designated
// constraints aren't met.
type ListSubmissionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSubmissionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSubmissionsResponseMultiError) AllErrors() []error { return m }

// ListSubmissionsResponseValidationError is the validation error returned by
// ListSubmissionsResponse.Validate if the designated constraints aren't met.
type ListSubmissionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSubmissionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSubmissionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSubmissionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSubmissionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSubmissionsResponseValidationError) ErrorName() string {
	return "ListSubmissionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListSubmissionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSubmissionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSubmissionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSubmissionsResponseValidationError{}

// Validate checks the field values on ListRecentSubmissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRecentSubmissionsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRecentSubmissionsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRecentSubmissionsRequestMultiError, or nil if none found.
func (m *ListRecentSubmissionsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRecentSubmissionsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListRecentSubmissionsRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListRecentSubmissionsRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListRecentSubmissionsRequestValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UserId

	// no validation rules for Limit

	if len(errors) > 0 {
		return ListRecentSubmissionsRequestMultiError(errors)
	}

	return nil
}

// ListRecentSubmissionsRequestMultiError is an error wrapping multiple
// validation errors returned by ListRecentSubmissionsRequest.ValidateAll() if
// the designated constraints aren't met.
type ListRecentSubmissionsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRecentSubmissionsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRecentSubmissionsRequestMultiError) AllErrors() []error { return m }

// ListRecentSubmissionsRequestValidationError is the validation error returned
// by ListRecentSubmissionsRequest.Validate if the designated constraints
// aren't met.
type ListRecentSubmissionsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRecentSubmissionsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRecentSubmissionsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRecentSubmissionsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRecentSubmissionsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRecentSubmissionsRequestValidationError) ErrorName() string {
	return "ListRecentSubmissionsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRecentSubmissionsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRecentSubmissionsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRecentSubmissionsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRecentSubmissionsRequestValidationError{}

// Validate checks the field values on ListRecentSubmissionsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRecentSubmissionsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRecentSubmissionsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListRecentSubmissionsResponseMultiError, or nil if none found.
func (m *ListRecentSubmissionsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRecentSubmissionsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRecentSubmissionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRecentSubmissionsResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRecentSubmissionsResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListRecentSubmissionsResponseMultiError(errors)
	}

	return nil
}

// ListRecentSubmissionsResponseMultiError is an error wrapping multiple
// validation errors returned by ListRecentSubmissionsResponse.ValidateAll()
// if the designated constraints aren't met.
type ListRecentSubmissionsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRecentSubmissionsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRecentSubmissionsResponseMultiError) AllErrors() []error { return m }

// ListRecentSubmissionsResponseValidationError is the validation error
// returned by ListRecentSubmissionsResponse.Validate if the designated
// constraints aren't met.
type ListRecentSubmissionsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRecentSubmissionsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRecentSubmissionsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRecentSubmissionsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRecentSubmissionsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRecentSubmissionsResponseValidationError) ErrorName() string {
	return "ListRecentSubmissionsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRecentSubmissionsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRecentSubmissionsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRecentSubmissionsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRecentSubmissionsResponseValidationError{}

// Validate checks the field values on GetJudgeResultRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetJudgeResultRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetJudgeResultRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetJudgeResultRequestMultiError, or nil if none found.
func (m *GetJudgeResultRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetJudgeResultRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetContext()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetJudgeResultRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetJudgeResultRequestValidationError{
					field:  "Context",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetContext()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetJudgeResultRequestValidationError{
				field:  "Context",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SubmissionId

	if len(errors) > 0 {
		return GetJudgeResultRequestMultiError(errors)
	}

	return nil
}

// GetJudgeResultRequestMultiError is an error wrapping multiple validation
// errors returned by GetJudgeResultRequest.ValidateAll() if the designated
// constraints aren't met.
type GetJudgeResultRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetJudgeResultRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetJudgeResultRequestMultiError) AllErrors() []error { return m }

// GetJudgeResultRequestValidationError is the validation error returned by
// GetJudgeResultRequest.Validate if the designated constraints aren't met.
type GetJudgeResultRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetJudgeResultRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetJudgeResultRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetJudgeResultRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetJudgeResultRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetJudgeResultRequestValidationError) ErrorName() string {
	return "GetJudgeResultRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetJudgeResultRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetJudgeResultRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetJudgeResultRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetJudgeResultRequestValidationError{}

// Validate checks the field values on GetJudgeResultResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetJudgeResultResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetJudgeResultResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetJudgeResultResponseMultiError, or nil if none found.
func (m *GetJudgeResultResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetJudgeResultResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetJudgeResultResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetJudgeResultResponseValidationError{
					field:  "Result",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetJudgeResultResponseValidationError{
				field:  "Result",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetJudgeResultResponseMultiError(errors)
	}

	return nil
}

// GetJudgeResultResponseMultiError is an error wrapping multiple validation
// errors returned by GetJudgeResultResponse.ValidateAll() if the designated
// constraints aren't met.
type GetJudgeResultResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetJudgeResultResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetJudgeResultResponseMultiError) AllErrors() []error { return m }

// GetJudgeResultResponseValidationError is the validation error returned by
// GetJudgeResultResponse.Validate if the designated constraints aren't met.
type GetJudgeResultResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetJudgeResultResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetJudgeResultResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetJudgeResultResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetJudgeResultResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetJudgeResultResponseValidationError) ErrorName() string {
	return "GetJudgeResultResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetJudgeResultResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetJudgeResultResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetJudgeResultResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetJudgeResultResponseValidationError{}
